share/container/containerd.go
share/osutil/user_linux.go
share/system/sysinfo/util.go

Missing some asset's information on k3s clusters.
(1) containerd: retriving container's privileged status via cri interface.
(2) os name: resolved symbolic link issue.
(3) removing messages from enforcer's logs:  "Get /etc/passwd fail".

NV6106 and NV6117: minor fixes on the k3s's asset information.

---

agent/probe/fsn.go

The path is equal to "/" which caused the panic condition.

NV6130: goroutine crash at probe.(*FileNotificationCtr).handleEvent()

---

agent/engine.go
agent/group_profile.go
agent/probe/process.go

Some reused sandbox will not create a new "pause" prcesses (observed at CRIO).

ZeroDrift: include sandbox process tree protection.

---

agent/engine.go
controller/cluster.go
controller/kv/create.go
dp/ctrl.c

to avoid implicit violation related to xff policy matching during upgrade, this is without changing XFF default as enabled.

NVSHAS-5942/5943, set internal xff default value on enforcer to disabled 

---

controller/rest/admwebhook.go

k8s(1.19, +)'s behavior: if only 'limit', but not 'request', value is specified in yaml, use 'limit' value as 'request' value

NVSHAS-5522: Admission Control Rule to enforce resource limitations.

---

agent/agent.go
agent/probe/process_test.go
agent/timer.go
share/container/containerd.go
share/container/crio.go
share/container/docker.go
share/container/types.go

For runtime-engine CRIO only: create 3 states (running, stop, deleted) of conatiners/pods while polling their status.

NV6134 patch: unable to detect exit status of parent pod on oc 4.9

---

agent/agent.go
agent/bench.go
agent/grpc.go
agent/probe/faccess_linux.go
agent/probe/fsn.go
agent/types.go
agent/workerlet/pathWalker/pathWalker.go
agent/workerlet/tasker.go
monitor/monitor.c
share/fsmon/monitor.go
share/scan/secrets/secrets.go

(1) To prevent pathWalkers from running into an indefinite state. 
(2) For debugging purpose, the enforcer will pass the container identifier to the pathWalker, too.

NV6145, NV6249 and NV6038: pathWalker updates.

---

share/container/common.go
share/orchestration/kubernetes.go

The original method used to prune common suffixes from the pod enumerations. Somehow, the newly installed cluster doe not follow the rules. However, the new clusters also provide more labels which we can identify the correct name of pods.

NV6146, NV6118: server group names are not in the expected format as usual on rke2 and oc49

---

agent/probe/process.go
share/clus_apis.go

Patch an incident type: when the new process from its image file is not from its root process, the violation incident should be reported.

NV6175: unexpected rule_id and message for zero-drift

---

agent/probe/process.go

To reduce the false-positive cases, we add some exceptions with detail checks to allow some host's routine checks. It still reports if the target file is not an image file.

Zero-Drift: no need to report violation incident on system's routine calls

---

controller/api/apis.go
controller/cache/cache.go
controller/cache/compliance.go
controller/cache/config.go
controller/cache/file_monitor.go
controller/cache/interface.go
controller/cache/object.go
controller/cache/policy.go
controller/common/common.go
controller/kv/create.go
controller/kv/upgrade.go
controller/rest/configmap.go
controller/rest/system.go
share/clus_apis.go

1. when global network service is enabled, the network policy mode will be globally set to discover/monitor/protect
2. at the per group level, user can still switch mode without behavior change, however per group level policy mode only applies to process profile, 
3. it is same for policy mode set by crd, it only applies to profile if global network service is enabled.
4. when global network service is disabled, per group level policy mode will apply to both network and profile.

NVSHAS-5545, add system configuration network service toggle to select cluster wide network policy mode

---

controller/resource/kubernetes_rbac.go
controller/rest/auth.go

further differentiate reader role in OpenShift context via checking "get", "list" and "watch" verbs
on the predefined resources

limit the reader role scope in OpenShift context

---

controller/api/apis.go
controller/atmo/atmo.go
controller/atmo/atmo_tasks.go
controller/atmo/atmo_test.go
controller/cache/automode.go
controller/cache/cache.go
controller/cache/config.go
controller/cache/group.go
controller/cache/object.go
controller/rest/configmap.go
controller/rest/system.go
share/clus_apis.go

Continuous protection upgrades (mode automation): 
Discover -> Monitor -> Protect
(1) Discover -> Monitor
Live service [members > 0] for a program-able period (minimum 60 seconds). It works as accumulated counters,
(2) Monitor -> Protect
No per-group process incidents  for a program-able period. (minimum 5 minutes)
* Not affecting the CRD groups and the global setting of the network mode.	
* Both default options are disabled, 
* Use timer wheel instead of loops through groups periodically.

NV5818: Mode automation upgrader

---

agent/policy/process.go
agent/probe/process.go
controller/cache/cache.go
controller/cache/group.go
controller/cache/object.go
controller/cache/profile.go
controller/common/common.go
controller/resource/kubernetes_resource.go
controller/resource/types.go
share/clus_apis.go
share/container/containerd.go

Patch for the Zero-drift baseline process profile
(1) The k8s probe process commands (like Liveness, Readiness, and Startup Probes) are added as allowing process rules by default.
(2) The Probe's children processes are allowed if their executables are not modified.

NV6264: unexpected Process.Profile.Violation incident on calico-node process if it triggered by readinessProbe

---

controller/api/apis.go
controller/common/output.go

This is to support Microsoft Teams support for WebHook notification, it has similar approach with Slack but with different JSON key. We still needs to add an option on the Web console for user to choose Teams.

6124,5833: Add Microsoft Teams support for WebHook notification

---

controller/common/common.go

New service configuration: set zero-drift process baseline profile as default

---

controller/resource/kubernetes_rbac.go

fix a side effect when adjusting mapping logic in OpenShift context.
applies for #6266, #6267

fix rbac mapping issue caused by adjusting OC rules side effect

---

controller/cache/object.go
controller/resource/kubernetes_resource.go
controller/resource/types.go
share/orchestration/docker.go
share/orchestration/ecs.go
share/orchestration/kubernetes.go
share/orchestration/noop.go
share/orchestration/rancher.go
share/orchestration/types.go
share/orchestration/unknown.go

It is not sufficient to capture a service group name from the pod information.  Add labels information from pods to clarify the relationship between pod names and service group names.

NV6274: k8s probe commands: process violation reported for calico controller pod

---

agent/agent.go
agent/engine.go
agent/group_profile.go
agent/policy/process.go
agent/probe/fsn.go
agent/probe/probe.go
agent/probe/process.go
agent/probe/process_test.go
agent/probe/types.go
controller/cache/cache.go
controller/cache/object.go
controller/cache/profile.go
controller/common/common.go
share/clus_apis.go
share/system/cgroup_linux.go
share/system/cgroup_test.go
share/system/system_linux.go

Zero-drift baseline profile: k8s probe enhancement:
(1) Consolidate duplicate Probe commands and allow multiple different probe command sections together.
(2) Improve shell script probe detection.
(3) Allow system pods with all privileges to use the binaries in the node.
(4) Fix a wrong detection on the pod's upper folders.
Tested on the oc 4.8 clusters.

NV6280 and NV6289: zero-drift, unexpected Process.Profile.Violation in the oc setup

---

controller/cache/group.go
controller/cache/object.go

We will count the running workloads, instead.

NV6291: show incorrect container count in GET /v1/host on oc setup

---

agent/probe/process.go

Multiple learn process events are okay because they are merged at controllers.

NV6332: ProcessProfile: Changing mode from monitor to discover do not learn process

---

agent/agent.go
agent/policy/process.go
agent/probe/faccess_linux.go
agent/probe/probe.go
agent/probe/process.go
agent/probe/types.go
controller/cache/group.go
controller/cache/object.go
controller/cache/profile.go
controller/resource/kubernetes_resource.go
controller/resource/types.go

(1) Add Get k8s pod resource API calls.
(2) Special cases for the zero-drift baseline process profile: if the pod has k8s probe command configuration, we allow "kubectl exec" executions but will not learn their external processes. We still treat modified/added binaries as suspicious processes if the binaries have been added or modified.

NV6308, NV6305, NV6313: k8s probe commands improvement.

---

controller/api/log_apis.go
controller/cache/automode.go
controller/common/common.go
share/clus_apis.go

(1) m2p: add threats and violations as checking items.
(2) put log events for promoting policy mode.
(3) remove `^M` from  "controller/cache/automode.go"

NV6348, NV6347: Improvement at the service group mode automation

---

agent/policy/process.go
agent/probe/fsn.go
agent/probe/process.go
share/osutil/process_linux.go

(1) NvPRotect: add allowed process rules for python3.9
(2) ZeroDrift: always allow rootPid.
(3) Update process name by removing its unnecessary prefix, "/" ,

NV6362, NV6363, NV6365: Unexpected Process.Profile.Violation events

---

controller/atmo/atmo_tasks.go

For the mode promotion from monitor to protect, it is the "quiet" time period AFTER no security event associated with this service group.

Automode: reset m2p counter when any security event occurs.

---

agent/engine.go
agent/group_profile.go
agent/probe/process.go
share/utils/utils.go

(1) The feeback path from process history storage is not correct. Thus, we might miss the learned processes at the beginning of the container additions.
(2) Change violation messages.
(3) The traceback processes should stop at root processes and put them as children processes.
(4) We will not monitor files under the mounted folders. Thus, we will not check them in zero-drift baseline profile.

NV6304, NV6380, NV6378: missing and false-positive processes

---

agent/probe/process.go

Zerodrift: allow learning processes from "kubectl exec" commands for pods which have k8s probe seting.

Zerodrift: allow learning processes for pods which have k8s probe setting

---

agent/probe/process.go

Different "runc init/create" commands on the cri-o platform.

NV6392: unexpected Process.Profile.Violation incidents on "runc init"

---

agent/policy/process.go
agent/probe/process.go

(1) The process rules can not be learned because the controller has inserted some probe command rules. 
(2) Double-checking the relationship between process name and path.

NV6398: process profile rule is unable to learn a complete rule set if they are inside a k8s probe commands.

---

agent/probe/fsn.go

For btrfs storage system, the new file logic is different from other storage systems. It needs to separate it from others.

NV6407: keep denying processes in app container on btrfs storage systems

---

agent/policy/process.go

When the NV pod exits, the monitor calls to execute a script to terminate its consul process. The paired set was ("consul", "/bin/busybox"),  -- the "consul" process is under the shell process --, especially when they are running on the latest coreos (oc410) environment.

NV6413: unexpected Process.Profile.Violation incident on consul process

---

share/container/docker.go
share/global/global.go

When we can not obtain a running container list, we can not decide on the platform and its subsystem. Give it more tries until it receives a non-empty container list.

NV6411: sometimes the platform info is missing in /v1/host api on native docker setup

---

controller/cache/interface.go
controller/cache/scan.go
controller/rest/scanner.go

(1) Support "/v1/scan/workload/:id" to include the complete module and cve list.
(2) Combined with scanner PR#32

NV6435: Add modules for container scan

---

agent/agent.go
controller/controller.go

k8s 1.24, containerd 1.6.4, and cgroup v2
The lookup self-container-identifier method fails with different pod labels. Implement more common elements to find the absent container identifier from the cgroup system.

NV6433: Enforcer is not becoming operational on k8s 1.24, 1.64 containerd cluster

---

agent/probe/process.go

The cmd length was 1 and caused the invalid slice index.

NV6449: goroutine crash at probe.isSudoCommand

---

agent/probe/incident_reporter.go
share/fsmon/inotify_linux.go
share/fsmon/monitor.go
share/fsmon/notify.go
share/osutil/file_linux.go

It was a new package installation method for the "bci" containers.
(1) Add package installation monitor for "zypper"/"rpm".
(2) Add 3 minutes report detection gap among installations. ( before that we only report once and then removed the monitor file mark)

NV6461: After installing a package in a container, the rescan is not triggered

---

share/system/cgroup_linux.go
share/system/cgroup_test.go

In the newer system/runtime version, the enforcer failed to find the container's correct ID but the pod ID, which cause confusion.
// crictl version: 1.24.0
// containerd: 1.6.4
// k8s: 1.24
(1) Change the searching method into a generic way
(2) Improve possible search target by reversing order.
(3) Add a new test case.

NV6468: lots unexpected Process.Profile.Violation are created in k8s 1.24 setup

---

agent/probe/process.go

It could be one of the bench commands executed in the worker node.
nstools -> sh -> grep
when the event came into the decision logic, it was gone. The insufficient information failed the skip decision.

NV6478: unexpected NV.Protect incident on grep command

---

agent/agent.go
controller/controller.go
share/global/global.go

Cause: the docker service was not responsive for a period of time, because we got an empty "docker ps" list (3 tries). The agent went into a non-recoverable failed state. Then, the container exited.
Patch: instead of the container's exit, let the monitor recover it by restarting the agent process until the agent obtains the correct result.

NV6502: enforcer is unable to start successfully sometimes

---

controller/cache/cache.go
controller/cache/object.go
controller/resource/kubernetes_resource.go

NV6342:
(1) The k8sHostInfoMap has not been added at  "hostUpdate()".
(2) The "global.ORCH.GetResource()" could fail with empty metadata but is considered a false-positive result.

NV6342: annotations is sometimes empty on one of oc 4.8 cluster nodes

---

controller/cache/admission.go
controller/cache/admission_test.go

Previously the "containsAny" operation in admission control would incorrectly resolve to false when given a criteria that contained multiple key/value pairs (formatted as "key=value"). It was due to the map implementation for the lower level functions only allowing one value per key. This change alters that map to allow multiple potential values per key to be checked and adds a related test case.

NVSHAS-6422: fixed containsAny admission control operation ignoring multiple values for same key

---

agent/agent.go
monitor/monitor.c

This patch aims to support setting dp debug level at dp startup by
defining environment variable `DEBUG_LEVEL="ctrl error"` in addtiton to the API way.

ENABLE Setting DP Debug level at startup

---

controller/kv/create.go
controller/kv/helper.go
controller/kv/upgrade.go

Add a one-time upgrade function for the new predefined file monitor entry.

NV6484: new added files for file monitor and file rule is not migrate d from old version

---

controller/cache/object.go
controller/cache/scan.go

Those error messages were correct because the enforcer was deleted and the controller has not the "deleted" event yet.
The issue is not we can not add the scanning task while the new enforcer is up.

Nv5225: host scan may fail after enforcer restarts

---

controller/cache/admission.go

When a criterion value for an admission control rule is something like `firstKey=firstValue, secondKey` the `secondKey` value would have a leading space that throws off comparison later in the logic. This just trims it out, a detail that was missed when fixing a previous bug.

hotfix: fixes leading or trailing spaces breaking certain admission control criterion values

---

share/container/containerd.go
share/container/crio.go

On k3s systems, the runtime grpc service call can not release its handles and memory. Thus, it creates memory leaks and unreleased socket handles/goroutines. To fix the memory leakages, we manually add a canceling context call for every service call. It applies to runtime drivers: containerd and crio. 
The unreleased goroutines also occupied the majority of the CPU usage in the customer's case.

NV6545: Agent process high cpu/memory usages

---

agent/agent.go
controller/controller.go
share/global/global.go

For k8s clusters with the cgroup v2 subsystem, we sometimes can not locate a correct nv containers' ID.  
(1) Remove the image role criteria from the matching method since the image label is absent in the rke2.
(2) Consolidate the lookup function into a common package.

NV6158: enforcer's info is sometimes from parent container

---

controller/cache/admission.go
controller/cache/admission_test.go
controller/nvk8sapi/nvvalidatewebhookcfg/admission/admission.go
controller/scan/interface.go
share/criteria.go

Adds the ability for users to create admission control rules based on module information in scanned images.
The new `modules` criterion follows the `key[=value]` schema that other admission rules use.
Examples:
The following will deny any deployment that contains the "curl" module/package in its scanned image at any version
```
criterion: modules
type: deny
operation: containsAny
value: curl
```
The following will deny any deployment that contains the "curl" module package with the specific version "1.1.1.1" in its scanned image
```
criterion: modules
type: deny
operation: containsAny
value: curl=1.1.1.1
```
The following will deny any deployment that contains the "curl" module package with the specific version "1.1.1.1" in its scanned image, or the "openssl" package at any version
``` …
```

NVSHAS-3842: add modules criteria to admssion control

---

agent/engine.go
agent/probe/process.go
share/container/crio.go

The CRI-O on the oc 4.9 and above: 
Their pod processes are removed and still have a container identifier. The bug cause is because the PID of the POD is 0; then, we considered the POD was ready in the active container table and held the data collecting issue.
(1) Report the correct container process list
(2) Redo the CRI-O driver to clarify the PID assignment. 
(3) Redo the CRI-0 driver to rely solely on the CRI API of the k8s functions.
(4) Realign the root process of a container from the CRI-O information.

NV6557: cri-o patches for oc 4.9 and above

---

share/container/crio.go

NIL pointers for debug traces.

NV6590: goroutine crash at the crioDriver

---

agent/probe/fsn.go

There are two procedures to verify the non-image files. One of these uses a wrong file path and causes false-negative cases.

NV6586: false-negative Process.Profile.Violation incidents on non-image processes

---

agent/agent.go
agent/bench.go
agent/cluster.go
agent/service.go
agent/types.go
monitor/monitor.c

It allows disabling CIS/docker bench tests on the hosts by providing an environment variable in the YAML file, like:
env:      
- name: ENF_NO_AUTO_BENCHMARK
value: "1"

Enforcer: add no cis/docker benchmark flag: env "ENF_NO_AUTO_BENCHMARK"

---

agent/probe/process.go

The process name is updated during the process evaluation. Thus, it does not report a proper suspicious process name in the incidents. Thus, users can not review or add correct process rules to suppress the incidents.

NV6558: Definined process rule is still triggering Security Events

---

agent/probe/process.go

For older docker runtime ("docker ce 18.x"), it might have a false-positive case with the in-memory execution.

NV6592: Unexpected process profile incident reported on natvice docker host

---

agent/probe/fsn.go

A follow-up patch of the NV6586 (PR#341) is for the btrfs subsystem.

FSN: adding process file detection for btrfs.

---

controller/cache/admission.go
controller/cache/admission_test.go

Version `5.1`
This change implements comparison operators for modules with semantic versions. A user, when creating an admission control rule for modules, will be able to use the new operators in the value field. For example, a module criterion value field of `vim>1.0.0` will check whether a scanned image has a the vim module with a greater version than `1.0.0`. These can be composed and combined in a number of powerful ways.
For example, to blacklist certain modules older than a certain version:
```
ruleType: "deny"
name: "module"
op: "containsAny"
value: "vim<2.0.0, curl<3.0.0, ssh<4.0.0"
```
The following operators are implemented: `>, <, >=, <=`
If a version comparison operator is used and either the criteria or module has an version that doesn't follow the semantic versioning syntax, …

NVSHAS-6576: Add Semantic Version Comparison to Modules Admission Rule

---

controller/cache/policy.go

In the attached enforcer log there are many repeated errors as follows:
2022-07-28T20:06:40.543|ERRO|AGT|policy.adjustAction: Missing policy mode for both src and dst! - from=646230859bb90cc28e2f2ee32b90fba68279fc8ba7aedc1120ec4cd5bbd9554d id=10115 to=nv.address_group
this fix try to correct this issue.

NVSHAS-6593, fixing 'Missing policy mode for both src and dst' issue

---

agent/engine.go

Extending nv pod identifications.

NVSHAS-6606: keep showing wait for parent for nv enforcer pod

---

share/container/containerd.go

The missing "defer" action of the context causes the immediate grpc disconnection.

NVSHAS-6502: enforcer is unable to start successfully

---

agent/bench.go

Include docker bench tests (host and containers) to be disabled together with the no-auto-benchmark flag.

Disable automatic bench tests: include docker bench tests

---

controller/cache/admission.go
controller/cache/admission_test.go
share/utils/version_test.go

The issue was the way I was "finding" the operator.
When a user enters a criterion value such as `myKey<=myExample`, the code previously resolved the operator as `=`. These changes establish hard checks for those possibilities, and may be worth extracting into its own type upon further expansion.

NVSHAS-6654 fix >= and <= operators in module admission control rule

---

share/criteria.go

(1) Restore the OR condition for the same criteria type.
(2) Separate namespace/pod labels as two different criteria types.

NVSHAS-6665: it was or condition with multiple key=value labels when creating a group

---

controller/cache/cache.go
controller/cache/domain.go

Part#1 controller side:  fix the correct PODs selected by the updated namespace labels.
This is from the k8s namespace resource watcher. It should not have our predefined domain, like "_images", "_containers" or "_nodes". Thus, the namespace data can be always updated during runtime. 
TODO: 
Part#2: enforcer side: re-calculate process/file profiles.

NVSHAS-6663: part#1, controller, new label on namespace is not added in kv consul

---

controller/cache/group.go

Restore the previous display to include child pods.

NVSHAS-6673: the child container is not a member in a user created group

---

agent/policy/process.go

The process policy handler passes a Deny decision when the process was not in the process rules. The zero-drift verification follows the decision and mistakes the process for the k8s probe groups

NVSHAS-6636: part#2, unexpected process profile violation reported for the Azure cluster in monitor mode

---

agent/group_profile.go
agent/system.go
controller/cache/domain.go
controller/cache/group.go

Part#2:
Complete the selections on both controller and enforcer (system profiles) when the namespace labels are modified.

NVSHAS-6663: part#2, new label on namespace is not added in kv consul

---

agent/engine.go
agent/group_profile.go
agent/probe/intf_linux.go
agent/probe/netlink/socket.go
agent/probe/process.go

For k8s systems, the POD's Pid is 0 and its network setting is not configured in host mode. 
(1)  Inspect one of the app containers to obtain the network interface information.
(2)  Remove unnecessary monitorings on the containers whose root Pid is 0.

NVSHAS-6635: unable to detect interface for app containers in oc 4.9

---

agent/probe/process.go
share/system/toolproc_mon.go

(1) Add process tree model into NV pods. They are allowing child processes from the root process to run.
(2) Referring agent's exec.Command pool to identify the child processes of the agent.

NVSHAS-6643: unexpected Process.Profile.Violation incident in NV.Protect group

---

agent/engine.go
share/container/containerd.go
share/container/crio.go
share/container/types.go

Container drivers: CRI-O and Containerd
(1) Retrieve extra image information from CRI: the image labels that help identify NV pods.
(2) Update the image's author name.
(3) To avoid the remote containerd's GRPC errors during Task() operation, it uses the CRI protocol to obtain its rootpid and running status.
(4) Update the nv updater's root command identity.

NVSHAS-6630: identify nv pod using labels of image

---

agent/engine.go
share/container/common.go
share/orchestration/docker.go
share/orchestration/ecs.go
share/orchestration/kubernetes.go

For example, the pod with the "io.neuvector.service.name=nginxABC" will belong to "nv.nginxABC"
------------------------
YAML: pod definitions:
-------------------------
metadata:
labels:
app: nginx
io.neuvector.service.name: nginxABC
--------------------
Group definitions:
--------------------
Group Name: 
nv.nginxABC.neuvector-1
Criteria:
service=nv.nginxABC.neuvector-1
domain=neuvector-1

NVSHAS-6689: Ability to change how native service group is created a specific label

---

agent/agent.go
agent/group_profile.go
agent/probe/probe.go
agent/probe/process.go
agent/probe/types.go
agent/types.go
monitor/monitor.c
share/fsmon/monitor.go

To minimize the enforcer's resource usage:
Add an environment variable:
env:
- name: ENF_NO_SYSTEM_PROFILES
value: "1"
Which will disable the system profiles (process and file monitors). No learning processes, no profile modes, no process/file (package) incidents, and no file activity monitor.

NVSHAS-6693: A flag to turn off runtime protection

---

controller/cache/group.go

When the namespace labels change, we should re-calculate the custom groups for nodes and adjust the necessary custom groups for the target nodes. In this case, it did not push the custom group into the node.

NVSHAS-6702: ProcessProfile: process from customer group created with namespace label is not added to container.

---

controller/cache/cache.go
controller/cache/node.go

To fill "connected" (online) for the host's state, It also corrects that the cancelHostRemoval() accidentally clears this data.
Next on the UI change: if UI receives this state, it should follow up by showing a "green" dot.

NVSHAS-6683: Node's State field value as empty string should be avoided

---

agent/bench.go

Modify logic to have no new (added) benchmark KV entries if the flag is enabled.
For example,
bench/<host id>/report/docker_container
bench/<host id>/report/docker_host
bench/<host id>/report/kube_master
bench/<host id>/report/kube_worker
and 
scan/state/bench/host/<host id>
scan/state/bench/workload/<container id>

NVSHAS-6790: no new benchmark info in kv if ENF_NO_AUTO_BENCHMARK is enabled

---

controller/rest/process.go

We support multiple process rule deletions at a time. The case is those process names are the same but have different paths.

NVSHAS-6718: Multiple process profile rules deletions

---

controller/cache/admission.go
controller/cache/pss.go
controller/cache/pss_test.go
controller/nvk8sapi/nvvalidatewebhookcfg/admission/admission.go
controller/rest/admwebhook.go
share/criteria.go

This implements an admission control rule that follows Kubernetes Policy Security Standards (https://kubernetes.io/docs/concepts/security/pod-security-standards/) with two exceptions:
1. The "HostProcess" check is not implemented since we do not support Windows
2. In the "Host Ports" check, there is no behavior related to allowing a "known" list. This is also the case in the Kubernetes source code, and every other vendor implementation I could find.
An additional change of note: ephemeral and init containers are being incorporated into admission control validation, however they are currently only checked by the PSS admission rule.
The updates to seccomp profile types will be included in another PR, as it requires changes to `go.mod` and `vendor`.

NVSHAS-6477 implement k8s pss admission rule

---

share/orchestration/kubernetes.go

According to k8s spec, the allowed k8s pod's meta name is:
metadata.name: Invalid value, a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9][a-z0-9])?(\.[a-z0-9]([-a-z0-9][a-z0-9])?)*')

NVSHAS-6689 #2: Ability to change how native service group is created with specific labels.

---

controller/cache/admission.go
controller/cache/pss.go
controller/cache/pss_test.go

Corrects some simple oversights and includes an additional check for an image running as root.
Deals with the following bugs:
- NVSHAS-6830
- NVSHAS-6832
- NVSHAS-6895

Nvshas 6477 bugfixes

---

controller/cache/admission.go
controller/cache/pss.go
controller/cache/pss_test.go

Ideally the validation logic wouldn't run again in order to capture the deny message, however this is a side effect of the deny message implementation which is noted in NVSHAS-6935.

NVSHAS-6886 fill deny rule message for pss/psa violations

---

agent/engine.go
share/container/common.go
share/container/crio.go

The case is duplicated by following similar command:
"kubectl create job --from cronjob/neuvector-updater-pod manual-run-jay.says.do.5 -n neuvector"
The syntax will create a user-defined POD name: "manual-run-jay.says.do.5"
Our current method can not identify that they were one of our pod names.
(1) enhance the identification method to cover this case.
(2) "cri-o driver": add image labels into container labels.

NVSHAS-6910: Manual trigger of Updater job cases NV to create a group for the container.

---

controller/rest/crdsecurityrule.go
controller/rest/group.go
share/orchestration/kubernetes.go
share/utils/utils.go

The pod name should be a validated entry to fulfill dns123 rules.

NVSHAS-6689: Adapting dns123 naming rule to correct improper pod names.

---

controller/rest/auth.go
controller/rest/federation.go

NVSHAS-6990: suggest to change wording from master cluster to primary cluster in the event
NVSHAS-6991: show internal hidden user ~fedOperator in the event when a worker cluster is kicked by master cluster

NVSHAS-6990 & NVSHAS-6991

---

agent/engine.go

On the CRI-O runtime, the updater pod was detected after it exited. The nv pod verification needs to be patched to accommodate the condition.

NVSHAS-6910: found exited updaters on the oc49's crio cluster

---

controller/cache/admission.go

to use the same format in audit log

NVSHAS-7023 Suggest put the criteria in () for risky-role audit log

---

controller/cache/pss.go

Fixes typo and clarifies that SYS_ADMIN capability is potentially causing privilege escalation.

NVSHAS-6978 minor updates to deny messages

---

share/scan/apps.go

Fixes an issue where vendorId and title can be malformatted during jar parsing.

NVSHAS-6653, fix for package names during jar parsing.

---

agent/cluster.go
agent/engine.go
controller/cache/object.go
share/container/common.go
share/orchestration/aliyun.go
share/orchestration/docker.go
share/orchestration/docker_test.go
share/orchestration/ecs.go
share/orchestration/kubernetes.go
share/orchestration/kubernetes_test.go
share/orchestration/noop.go
share/orchestration/rancher.go
share/orchestration/types.go
share/orchestration/unknown.go

Eliminate the hash-like identifiers :
(1) label "ClusterID"
(2) label "ibm-cloud-provider-ip"
(3) UUID strings
(4) Node name.
Plus test cases.

Service names updates: reducing the similiar randomized hash in the group names.

---

agent/policy/process.go
agent/probe/faccess_linux.go
controller/common/common.go

Merging "learned" processes rules for the same name but from the same root path (at least one matched parent path token):
a process pair ( name,    path )
(1)   "sleep", "/tmp/my/1/sleep")
(2)   "sleep", "/tmp/my/2/sleep"
merged ==> ( "sleep", "/tmp/my/*/sleep" ), replace rule (1) by the new rule
(3)  ("sleep", "/tmp/my/3/sleep")
consider as rule (2) ===>  ( "sleep", "/tmp/my/*/sleep" ), no new rule
Note: we will not learn "not-image" binaries with the "zero-drift" baseline process profile during Discover mode. You can use the "basic" baseline profile to test them in your containers.

NVSHAS-7182: Nessus agent create processes at randomized path, which makes very big process profile

---

share/orchestration/kubernetes.go

Add more tightly matching requirements by the node names to avoid the possible overlapping string with the pod's characters.

NVSHAS-7288 patch: Add matching requirement while a short node name is used

---

agent/cluster.go

k8s environment:
It occurs when the enforcer tried to add an exited child container and its parent pod was already gone. The inherited service name assignment hits empty parent data.

NVSHAS-7300: enforcer panic when a k8s container inherited the service name from its exited parent pod

---

share/container/containerd.go

The mismatched grpc versions cause the miss-parsing error strings of the remote server.

containerd driver: Suppress unnecessary stack error outputs because of the unmatched grpc versions.

---

agent/bench.go
agent/cluster.go
agent/engine.go
agent/group_profile.go

Refer to the service and domain names from the engine and remove the unnecessary getParent function at the cluster operations.

NVSHAS-7321: goroutine crash at container.(*containerdDriver).GetParent

---

agent/cluster.go
share/container/containerd.go

"containerd": the short-lived containers fail to under their running parent pods because the containerd driver does not provide the sandbox identifiers and we can not relate their pod relationship.
Add a sandbox identifier for a child pod which we already have for the cri-o runtime driver.

NVSHAS-6992: Pod is at running state but its exited containers were not under the pod.

---

share/container/docker.go
share/container/dockerclient/types.go

Add the container's sandbox identifier for docker runtime.

NVSHAS-6992: docker, Pod is at running state but its exited containers were not under the pod

---

agent/bench.go
agent/probe/process.go
share/fsmon/fanotify_linux.go
share/fsmon/monitor.go

Move them into debug-level messages since the container was exited before we investigated it.

Some unnecessary enforcer's log traces are suppressed for reducing i/o accesses

---

agent/probe/process.go

The issue was that when you do a `docker exec --user <user> ...` the nv agent would pick up the host' username instead of the container's username (they share the same uid). I figured out that when we're doing the evaluation, that the process' filepaths look correct but getting the wrong user from `/etc/passwd`. But that wasn't true since the path was correct - it was because the username was inherited by the parent by default and never updated again.

NVSHAS-7054 [agent] Added a line of code to update proc user(name) when it is getting evaluated.

---

agent/probe/process.go

We hit an error with patchRuntimeUser() with error: fatal error: concurrent map read and map write
So we need to add a lock around it at process.go:1825 to prevent the issue.

NVSHAS-7471 concurrent map read/write fix

---

agent/cluster.go

docker subsystem: no container meta information from a container stop event.

NVSHAS-7494: goroutine crash at main.putContainerForStop

---

agent/probe/process.go

When collecting the support log, the panic condition occurs with the no runtime protection flag.

NVSHAS-7511: goroutine crash by disabling a feature flag.

---

agent/probe/process.go

because a user saw panics due to concurrent map writes.

Adding locks around p.checkUserGroup_uidChange(parent, c) 

---

controller/api/apis.go
controller/rest/group.go
controller/rest/system.go

UI expects a consistent user experience that REST API "/v1/system/request" can work as "/v1/service/config" to alter the baseline process profiles.

NVSHAS-7345: Implement switching baseline profile in POST(/v1/system/request)

---

controller/rest/crdsecurityrule.go

Previously the metadata name was only checked when the `reviewType` was `share.ReviewTypeCRD`. The handler for admission control rule/config imports sends a `reviewType` of `share.ReviewTypeImportAdmCtrl`.
Perhaps this validation could be abstracted upwards.

NVSHAS-7482 disallow non-local metadata names in admission control import

---

agent/probe/process.go

I added a check in procProfileEval() so it will ignore the
reported flags when we are in Protect mode. I noticed that when we
transition from monitor -> protect, we don't track the state change and
reset the flags. So even tho the logs say that the process is in
violation, we do not attempt to kill it. So my change is to ignore the
reported flags when we are in Protect mode.
The reason is that regardless of the reporting flags, when we're in
protect mode, we should always be trying to kill violating processes and
not base the decision on the reported flag which is meant for
reducing message spam.

NVSHAS-7501

---

agent/agent.go
agent/engine.go
agent/system.go
agent/types.go
monitor/monitor.c

Add network policy pulling regulator at enforcers by adding an environmental variable on enforcers:
- name: ENF_NETPOLICY_PULL_INTERVAL
value: "60"        
The parameter to adjust the pull timer. default: 0 (or without this variable), it keeps the original inline behaviors, 
Other values ("N") in seconds will have the assisted regulator:  
(1) positive value: It is regulated for at least N seconds pulling breaks. (No pull within N seconds).
(2) negative value: no network policy pull.

Network policy pull regulator

---

agent/probe/process.go

When the runtime protection is disabled, we also disable UID escalation evaluation.

NVSHAS-7563: Enforcer traceback when runtime protection is disabled

---

controller/common/output.go

Fixed an issue where non json format syslog messages would include json "-" tag. This would cause excluded json fields to be included in non json output for syslogger.

 NVSHAS-5830 fix for struct2Text

---

agent/timer.go
controller/controller.go
share/cluster/consul.go
share/cluster/watch/plan.go
share/system/cgroup_linux.go

Enforcer has a cgroup memory reset 10-minute routine which will trigger container processes to reclaim unused memory and ask the kernel to recalculate the container memory usage. When this event begins, the Kernel will make the running container processes a new memory allocation. Thus, it could create an unexpected IO READ.
Currently, this PR increases the ceiling of container memory. Thus, regular enforcers (below 1.5 GB) and controllers (below 4GB) will NOT kick these triggers. The k8s resource limits will overwrite the settings and trigger this OOM protection situation as necessary.
Also, including some minor bug fixes of the consul watch utility functions and a performance configuration.

NVSHAS-7439: High Disk IO is observed when nodes are rebooted

---

controller/api/apis.go
controller/api/apis.yaml
controller/cache/domain.go

Append Nameapce's labels via a REST API call: GET "/v1/domain"
(1) Add REST entry:
type RESTDomain struct {
.........
Labels           map[string]string `json:"labels"`
}
(2) Update CLI response: "show domain".
(3) Update swagger data.

NVSHAS-6695: Expose namespace label in REST API

---

share/scan/scan_utils.go

Fixed an issue where var/lib/dpkg/status.d/ packages weren't handled properly on running containers causing modules to be unreported.

NVSHAS-7487 fixed an issue with var/lib/dpkg/status.d/ packages

---

controller/rest/registry.go

The critical issue identified by the static analysis tool on the Neuvector codebase. Specifically:
- controller/rest/registry.go, registry.go:[1140:49]. After having been compared to a nil value at registry.go:1140 (first half of "if" statement), pointer 'o.AwsKey' (as well as 'n.AwsKey') is dereferenced at registry.go:1140.
Сreated a pull request in which a change was added to the code to eliminate this error.

fixed dereference after comparison to nil

---

agent/bench.go

Move the k8s-check done flags before the log events.

NVSHAS-7716: Compliance.Host.Violation audit event is missing in k8s if the container runtime is not docker

---

controller/cache/cache.go
controller/cache/domain.go
controller/controller.go
monitor/monitor.c

With the k8s environment variable flag,
- name: CTRL_PRUNE_NSGROUPS
value: "1"
We will prune the groups, network policy, and response rules d in 2-3 minutes after the associated namespace was deleted.

NVSHAS-7700: Add a flag to enable the pruning groups/policy/response rules when its namesapce was deleted

---

agent/policy/process.go
agent/probe/process.go

During the “Protect” mode, an external process will be rejected if the process rule is not allowed explicitly by users.
Before:
Whenever it matches an allow process rule, we also allow it. (a white-list concept)
After:
* Even if it matched a “learned” type process rule, it will be rejected.
* Users need to add/apply the (learned) process rule manually to let it become a “user-created” rule type in order to allow the matched external processes. (UI needs to show the difference).

NVSHAS-7680: Zero-drift: Unabled to block external process because an allowed learned rule

---

agent/probe/incident_reporter.go
share/fsmon/inotify_linux.go
share/fsmon/monitor.go
share/fsmon/notify.go

(1) Support inode operations: the inode commands are "rm", "mv", "chmod", "chown" and so on.
(2) Modify Incident reporter to filter duplicate file monitor events.

NVSHAS-6804: file access rules not working for rm command

---

controller/api/apis.go
controller/api/apis.yaml
controller/rest/server.go
share/auth/auth.go
share/clus_apis.go

In SAML setting, user can input several certificates.

NVSHAS-7335 Allow several ADFS certificates in x.509 certificate field.

---

controller/rest/dlp_rule.go
dp/dpi/parsers/dpi_sqlinjection.c

1. Add SQLi signatures to detect more common SQLi (includes SLEEP, BENCHMARK, WAITFOR DELAY, ect.)
2. Rephrase comments in dlp_rule.go

[NVSHAS-7699] Improve SQLi detection in dp

---

share/container/containerd.go
share/container/cri_client.go
share/container/crio.go
share/container/docker.go
share/container/dockerclient/types.go

For enforcers, add the reConnect() for the docker, containerd, and cri-o runtime services. The leading cause is the mounted runtime socket, which will not update its inode data during runtime service restarts. If the reconnections do not work out for certain tries, it will trigger this enforcer pod restart,
It retrieves the host's socket endpoint from the container information to facilitate reconnections.

NVSHAS-7735: Restart k3s service, enforcer pod enters error loop

---

controller/cache/group.go

When the groups meet the pruning schedule and unmanaged nodes, the dispatcher will fail the group creation conditions. Patch a loose condition to ensure the leaned group creations.

NVSHAS-7769: 5.0.6, see group without namespace and unmatching group and members

---

share/fsmon/monitor.go

The file-changed handler fails to process the wr_closed events.

The Host.FileAccess.Violation incidents are missing after an linux user is added and modified

---

share/container/cri_client.go
share/container/crio.go

CRI_O only. The GRPC buffers for the CRI are not big enough to allow all data to pull back from the runtime. In this case, the oc49 has more than 2000 exited pods and the remote side created the errors. To patch this, we can separate the query data by filters and it could relieve the issues.

NVSHAS-7614: Container list is empty error happened in controller somehow in oc 4.9

---

controller/common/common.go

When the not-learned process rule was inserted, we did not update the rule type before. Add this patch.

NVSHAS-7801: In process profile rule page, backend combines rules with h the same name but the cfg-type value is not right

---

agent/probe/faccess_linux.go
agent/probe/process.go
share/container/docker.go

Note, Replacing https://github.com/neuvector/neuvector/pull/645
The original code gave "ps" a blanket exception which could allow things to fall thru. So in this PR, I closed the hole with checks to make sure the parent is runtime process for exceptions. Docker/kube will sometimes check on a container using `ps` in the background and this would throw false positives incidents.

Nvshas 7649 - Applying checks on process "ps" to determine exception

---

agent/probe/process.go
share/container/docker.go
share/system/system_linux.go
share/utils/utils.go

Zero-drift baseline process profile: We consider the mounted directories in the containers as internal files. Patch a bug to distinguish the sub-directory from a mounted point.

NVSHAS-7768: Process from a mounted directory being blocked by NeuVector even if it is whitelisted

---

controller/access/access.go
controller/access/access_test.go
controller/rest/auth.go
controller/rest/federation.go
controller/rest/user.go

- NVSHAS-7818
- NVSHAS-7825
- NVSHAS-7826
- NVSHAS-7808
- NVSHAS-7795
- NVSHAS-7796
- max length of apikey.name is 32
- apikey cannot bind fedAdmin/fedReader

NVSHAS-7825 and various API key cases

---

dp/main.c

Initialize context->quar to false when process pcap packets

NVSHAS-7450: Fix dp to detect pcap packets

---

share/fsmon/monitor.go

Patching the file event mask with the file-modified flag.

NVSHAS-7844: unable to create Container.FileAccess.Violation incident successfully if file is modified

---

agent/probe/incident_reporter.go

File events accumulator: restore empty file path if the same file has been reported in a period of time.

NVSHAS-7837: the file_path info is missing in Host.FileAccess.Violation incident

---

agent/probe/process.go

Zero-drift: the suspicious processes from the root process need to be alerted or denied.

NVSHAS-7836: Netcat is not alerted in monitor node with zero-drift enabled

---

agent/group_profile.go
agent/probe/faccess_linux.go

Patch the empty reference when the container was exited before its incident reports.

NVSHAS-7849: patch empty service group name for exited containers during Protect mode

---

agent/timer.go
share/container/crio.go
share/container/docker.go

(1) Reducing the container STOP events from the timer scans. 
(2) Patch an error from PR#739.
(3) Add runtime processes of the docker engine.

NVSHAS-7897 : enforcer keeps receiving stop container event from crio

---

controller/api/apis.go
controller/kv/helper.go
controller/rest/rest.go
share/clus_apis.go
share/scan/registry.go

Previously standard Golang errors would be returned by `(*RegistryClient).GetSignatureDataForImage` but now it will return NeuVector scan error codes for the sake of consistency.
This PR also includes minor formatting changes performed automatically by go-fmt for certain files.

NVSHAS-6217: Use Scan Error Code + Linting

---

share/cluster/api/status.go

The consul API requests from the leader watcher might enter an indefinite wait when the leader is missing. In this case, the DNS record was incorrect. 
To avoid the indefinite wait, this PR adds a timeout; then the watcher gets leader changes in time.

NVSHAS-7941: the workload event may be missing during lead change

---

agent/probe/incident_reporter.go
share/fsmon/monitor.go

NVSHAS-7844: "unable to create Container.FileAccess.Violation incident successfully if the file is modified"
--  There is another filter by a federal group referenced first to report incidents. We need to match all possible rules and report all possible learned process requests to controllers.
NVSHAS-3170: "Host.FileAccess.Violation incidents are missing" 
-- The aggregate incident worker's behavior was changed by the previous PR#821. The count must be incremented for the catchup events, too.

NVSHAS-7844, NVSHAS-3170: file monitor patches

---

agent/engine.go

docker and containerd:
The container info shows that it is still running. The enforcer should wait for the actual container "stop" events. The updated "stop" container info will be updated from these two runtime event listeners.

NVSHAS-7954: show running in workload object for the stopped container

---

agent/policy/process.go
agent/probe/process.go

NV Protect:
(1) Add allowed rules of the CSP pods.
(2) Add CIS benchmarks app tools to allinone and Enforcer only.
Adding NVSHAS-7914: Avoid intercept the traffic for process sigstore-interface in scanner container

NVSHAS-7938, NVSHAS-7951: unexpected NV.Protect incident is created

---

controller/cache/group.go

The comment is no longer empty when you get a service.

update: Includes group comment in service

---

controller/cache/scan.go
controller/scan/image.go
controller/scan/interface.go

The verifiers will now be included within the scan result response, and can be seen by the registry scan and admission control.

NVSHAS-6217: update scan result correctly

---

agent/probe/process.go
controller/cache/cache.go
controller/cache/group.go
controller/cache/object.go

Controllers:
(1) Add pod name display with nv pods.
(2) Add nv pod/group names identification function.
Enforcers:
Add calico-node processes.

NVSHAS-7983: NV protect events are not reporting name of the pod for manager, scanner and csp pods

---

agent/engine.go

containerd:
Its callback monitor does not reflect the not-running status but showed its exited time.

NVSHAS-7954: containerd, show running in workload object for the stopped container

---

controller/scan/image.go
controller/scan/jfrog.go
controller/scan/openshift.go
controller/scan/registry.go
share/scan/registry.go
share/scan/registry/manifest.go

For 7984:
Some registries (quay.io), instead of returning an error like we expect (for example "Accept header does not support OCI manifests") will return a morphed version of the requested manifest, meant to be compatible with whatever schema headers the request was made with.
This is meant to ensure that requests for signature image manifests always include the correct media type (application/vnd.oci.image.manifest.v1+json).
For 7957:
If an image is determined to be a signature image, it is not scanned. For an image to be considered a signature image, all of its layers must be of the media type `application/vnd.dev.cosign.simplesigning.v1+json`, which is the cosign specific mediatype for signatures.
The `QuaySpecialCase` logic is meant to handle the odd issue that arises with how Quay …

NVSHAS-7957 & NVSHAS-7984

---

agent/engine.go

docker runtime engine only:
There are two notifications from the docker watcher. The first event has the "FinishedAt". The second event includes the correct "exit" code. However, the containerd does not have the 2nd event. We need to add a check on waiting for the docker event's second event.

NVSHAS-8048: exit_code is not correct if container is stopped in native docker setup

---

agent/bench.go
agent/cluster.go
agent/engine.go
agent/group_profile.go

The service name was not constructed correctly that causes the mismatched service name and failure to select workload targets.

NVSHAS-8038: CustomCheck is not working for pods on kubernetes cluster

---

agent/engine.go

At enforcers (runtime: containerd/docker), the nv app pods are not reported to the controller.

NVSHAS-7983 v2: NV protect events are not reporting name of the pod for manager, scanner and csp pods.

---

agent/cluster.go
agent/engine.go

When we detect the container's stop event, the previous nv pod was not established because its rootPid process was exited.

NVSHAS-8080: neuvector csp container will be added into workload object

---

agent/probe/process.go

Previously, there is an edge case where deleting and reusing uids will cause nv to not update its cache.
If you create a user and then execute an violation. The user map will be updated. 
Delete the user and them add another user and reuse the deleted user's uid. Before the fix, the name would show the old one and not the new one.
Now cause a violation and the username will be correct.

NVSHAS-7418 - Changed getUserName() so it updates the container's username list

---

agent/agent.go
agent/probe/probe.go
agent/probe/process_test.go
controller/controller.go
share/container/containerd.go
share/container/cri_client.go
share/container/crio.go
share/container/docker.go
share/container/types.go

The cgroup v2 will hide its container id from the process information. Thus, you can not read your container id from the container's own processes.
The controller/enforcer might fail to report its sandbox id instead of its container id on the cgroup v2 with some runtime engines. The new method is using the CRI API to match the proper criteria(s) to find the correct app's container id.

Obtain correct app container id for enforcers and controllers.

---

agent/policy/process.go

The CIS bench scripts need "which" to identify the node's utility command paths. Add an allow rule for allinone and enforcer profile.

NVSHAS-8109: unexpected NV.Protect incidents are found

---

agent/probe/process.go

Found a bug in pipeline tests that found that this was updating a map and sendProcessIncident is used as a go routine. This caused a concurrent map write and the solution is to add a lock to make it safe

NVSHAS-8108 - Adding locks because getUpdatedUsername 

---

agent/policy/process.go

(1) NV-8114: the process rule, "stat" was missing from the allinone profile.
(2) NV-8109: add the process rule, "dash", for manager (cli), enforcer, and allinone.

NVSHAS-8114, NVSHAS-8109: false-positive cases for the NV Protect events

---

agent/engine.go
agent/group_profile.go

Add pod-level inclusion of the matching custom group criteria on the process/file profile membership.

NVSHAS-8136(enforcer update): container is selected based on image=xxx criteria, add related containers to group

---

agent/probe/process.go

Shorten the "cmd" by 32 characters to protect the secret content.

NVSHAS-7949: suggest to not showing the sensitive info in debug log

---

agent/agent.go
agent/cluster.go
agent/service.go
agent/timer.go
agent/types.go
controller/cluster.go
controller/controller.go
controller/grpc.go
monitor/monitor.c
share/types.go
share/utils/perf.go
share/utils/utils.go

(1) Environmental variable to enable the feature: "AUTO_PROFILE_COLLECT"
k8s example:
```
name: AUTO_PROFILE_COLLECT
value: "1"
```
(2) Triggered by the memory pressure (cgroup v1) event and the routine memory checks( ideally, 60%, 70%, 80%, 90%, and peak memory threshold: cgroup v1/v2). We keep a maximum peak memory record when either of the two events is reached their thresholds.
```
(a) memory pressure event: equal or above LEVEL 2
(b) routine memory checks: 60% and above of the defined memory limit( if not set, our default memory threshold)
```
(3) It will record the highest memory peak package (a zipped file):
```
enforcer: "/var/neuvector/snapshot/enf.snapshot.<containerID>.[1,2,3,4,p].zip"
controller: "/var/neuvector/snapshot/ctl.snapshot.<containerID>.[1,2,3,4,p].zip"
```
(4) The …

NVSHAS-8170: Auto profile collection feature to capture profile data at the maximum memory

---

agent/agent.go
agent/cluster.go
agent/timer.go
agent/types.go
controller/cluster.go
controller/controller.go
monitor/monitor.c
share/utils/perf.go

(1) Make the auto-profile as default setting( no required flag)
(2) Adjustable memory threshold.
For example, without a k8s resource limits:
(1) AUTO_PROFILE_COLLECT=0, no snapshot.
(2) AUTO_PROFILE_COLLECT=1 (default), snapshots above 60% of the ctl[6GB <= 3.6GB] and enf[3GB <= 1.8GB]
(3) AUTO_PROFILE_COLLECT=300 (300MB), snapshots above 60% of 300MB <= 180MB
(4) AUTO_PROFILE_COLLECT=-100 (invalid), no snapshot.

NVSHAS-8170 v2: make auto-profile default and adjustable memory threshold

---

controller/cache/group.go

"switch mode" should be grayed out for nodes group when it's crd-type

NVSHAS-8082: Not able to edit or delete process rules created using review rules from security events.

---

share/system/system_linux.go
share/system/toolproc_mon.go

Some agent's children's processes run swiftly and our process monitor can not probe them in time. Then, those who exited tool processes would not be traced by their ancestors and considered "nv protect" incidents. A good retaining record will improve the false-positive events.

NV Protect: keep temporary agent's process records to improve the false-positive cases

---

controller/api/apis.yaml

The current API doc only supports authentication using the `X-Auth-Token` header.
This PR enhances the API doc to include support for authentication using the `X-Auth-ApiKey` header.
First, introduced new securityDefinitions that support both `X-Auth-Token` and `X-Auth-Apikey` headers.
This allows users to authenticate using either header.
```yaml
securityDefinitions:
ApiKeyAuth:
type: apiKey
in: header
name: X-Auth-Apikey
TokenAuth:
type: apiKey
in: header
name: X-Auth-Token
```
Second, the security mechanism has been updated in the API paths to use the new securityDefinitions,
enabling flexible authentication header.
Use security instead of `X-Auth-Token` header in the paths:
```yaml
paths:
/v1/admission/options:
get:
tags:
- Admission
summary: Get a list of admission options
security: …
```

Add ApiKey support to the API doc

---

agent/probe/incident_reporter.go
share/fsmon/monitor.go

For v5.2.1,
(1) File report aggregator: redo the state machine.
(2) File monitor: returning "linkto" path instead of the symbolic link file if it exists.

NVSHAS-8051: FileMonitor events are not getting aggregated

---

agent/engine.go
agent/timer.go
share/system/cgroup_linux.go
share/system/cgroup_test.go

Changed getMemoryStats() to return an error for no files found.
Changed updateContainerStats() to deal with errors. There is a check if the container is a pod holder as those errors are valid under certain OS.
Added error handling when we first register a container in fillContainerProperties(). If the cgroup files fail to load, we blank out the path and never process it again. This should silence the errors in the logs with at least one message.

NVSHAS 7990 & 7925 - cgroup error log fixes

---

controller/rest/auth.go
controller/rest/rest.go

This commit allows user to use a separate JWT signing key when available.

NVSHAS-8212: allow using separate keys for jwt token

---

controller/cache/log.go
controller/common/output.go

Suppress those relative error messages by every 30 minutes. When the target address or certificate path changes, we reset the timer again.

NVSHAS-7764: "Maximum concurrent syslog message reached Check syslog server settings " ERROR log can be rate limited

---

agent/agent.go
agent/bench.go
agent/types.go
controller/controller.go
monitor/monitor.c

Default: custom benchmarks are disabled.
Enable this feature: both enforcer/controller deployments have the environment variable. 
- name: ENABLE_CUSTOM_CHECK
value: "1"
Note:  no custom benchmark, you can assign the value: "0"    
The enforcer part has been implemented.
The controller part: new variable: "ctrlEnv.customBenchmark".

NVSHAS-8289: Use env variable in enforcer for enabling/disabling custom benchmark

---

agent/probe/fsn.go
share/fsmon/fanotify_linux.go
share/fsmon/monitor.go

Two improvements
(1) The rapid file creation causes a huge amount of goroutines and the enforcer can not near half millions of workers together. Remove goroutines from the container's upper layer file monitor. 
(2) When the test pod has been removed, the file monitor will keep reporting events and set up its notify paths.  Reducing the footprints of the allocated structures and the stop reports will help a faster memory usage decline.

NVSHAS-8275: [Enforcer] Creating about 800K files under monitored directory causes enforcer memory bloat to 5G

---

controller/kv/dispatcher.go

Adding a function called AddNodeToCustomGroup() to synchronize the followers with the leader. This function updates dpt.group2node set so its always up to date with the WorkloadJoin/Leave events.
Before, if a leadership transfered happened to a follower, custom scripts would stop getting updated because the group2node set was always empty. We had only updated the set on the leader in the WorkloadJoin() function. So followers wouldn't update their set until all the clients rejoined the cluster.
WorkloadLeave() didn't have this issue because it called dpt.purgeCustomGroupsByNodeGroups() which would clean group2node for both leader & follower.
refreshServiceGroup2Nodes() looks like it should update the group2nodes set but custom groups are part of the function arguments so it can't refresh …

NVSHAS-8111 - Custom scripts not running

---

controller/cache/admission.go
controller/cache/interface.go
controller/rest/admwebhook.go

This appends a list of each violated deny rule and the problematic images on a per rule basis.
It looks like this:

NVSHAS-7704: show all deny rule violations during configuration assessment

---

controller/cache/scan.go

Fix the nil results from the scanner side. Adding a positive scan-in-progress condition into the next scan queue.
`grpc: server failed to encode response: rpc error: code = Internal desc = grpc: error while marshaling: proto: Marshal called with nil`

NVSHAS-8304: Scans failing on one Node only

---

dp/dpi/parsers/dpi_sqlinjection.c

Remove =" and =' in SQLi signatures as they may result in false positive detection.

NVSHAS-8319: Modify SQLi signature to prevent false positive

---

controller/scan/registry.go

The controller correctly checks whether an unscanned image is signed, skipping signature scans for unsigned images. The skip logic has also been cleared up.

NVSHAS-8322 & NVSHAS-8323: fix unnecessary signature rescans

---

agent/cluster.go
agent/system.go
controller/cache/learn.go
controller/cache/policy.go
controller/kv/helper.go
share/clus_apis.go

in current design, controller calculate network policy and push to consul, every enforcer will get same copy of policy regardless whether it is relevant to this node or not.
in this patch, controller calculate policy and reorgnize them into host-aware policy, so each enforcer only watch policy that relate to this node.
for k8s platform, whether policy is needed at node generally depends on "To" group, but in some special case it also depends on "From" group of policy.
for oc platform, whether policy is needed at node generally depends on "From" group, but in some special case it also depends on "To" group of policy.
containers group, mixed mode group , external, nodes and address group are treated differently to decide policy's desitination node.

NVSHAS-8226, Distribute network policy to enforcer with host awareness

---

controller/cache/learn.go

No need to update FQDN field in graph if it has value but the updated connection's FQDN field is empty. This may be due to the IP-FQDN record has timed out.

NVSHAS-5703: Improve update FQDN field in graph

---

controller/rest/rest.go

JWT certificate could be reloaded in a different time from when new cert is created.  Adding logs to indicate the cert reloading.

NVSHAS-5703: add extra logs for certificate reload

---

agent/probe/incident_reporter.go
share/fsmon/monitor.go

(1) the hash data was not initialized before the new file modified event.
(2) correct the file manipulation process slices. 
(3) filter out the reported file events with an empty file path.

NVSHAS-8327: FileMonitor: Many automation cases fail due to many fields missing in the event.

---

controller/grpc.go

Improve scannerRegister function:
(1) slot allocation from slot=127
(2) KV writes 
(3) Use deleteTree to remove previously-stored DB.
The performance comparison is listed in this JIRA case.

NVSHAS-8340: unexpected scannerRegister lock error in controller

---

agent/probe/faccess_linux.go

Added fixes to alleviate the issue.
* We get the process' parent path now. The issue before was that we were passing the path of the process to isParentProcessException(). This would not give a root process an exception because the function would not be able to get determine the parent's info. Now that I have the parent's path and passed it to the function, the process is given the exception.

NVSHAS-8053 - 'ps' process incidents are raised by root process

---

controller/grpc.go

Reverse the put scanner db operations from transactions into KV puts.
According to consul documentation, it limits the maxi transaction length (total request content length)  to 512 KB to retain its performance requirement.

NVSHAS-8373: fail to write cvedb into consul kv

---

controller/cache/node.go

When scheduleHostRemoval() is called due to agent is deleted or new controller lead election, it will add a task to delete host from cluster, then set the timeout timer to 10 mins. During that period, host may have an agent added. After 10 mins timeout, controller will check if the host has an agent on it. If the host has an agent on it, it should set the state to 'connected'. (The current behaviour is setting the state to empty)

NVSHAS-8313 Fix node state shows 'un-managed' but enforcer shows 'connected'

---

controller/api/apis.go
controller/api/apis.yaml
controller/cache/learn_test.go
controller/cache/object.go
controller/rest/workload.go
controller/scan/registry.go
controller/scan/scan.go

Add a flag which indicates the registry scan status of a workload.
api.RESTWorkloadBrief and api.RESTWorkloadBriefv2
ImgRegScand          bool          `json:"image_reg_scanned"`

NVSHAS-5774: Assets > Containers: Show containers that were scanned in registry

---

controller/cluster.go
controller/controller.go
controller/orch.go

Fixed this goroutine crash, which happens when doing string comparison.
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xda77b4]
goroutine 256 [running]:
main.(*orchConn).cbWatcherState(0xc00000f480, 0x2ce7b90, 0x9, 0x0, 0x0)
/go/src/github.com/neuvector/neuvector/controller/orch.go:37 +0x423
github.com/neuvector/neuvector/controller/resource.(*kubernetes).startWatchResource.func1(0xc0000c6a10, 0x0, 0x0, 0xc0000aacf0, 0xc00098aeb0, 0x2ce81c0, 0x9, 0xc00098aea0)
/go/src/github.com/neuvector/neuvector/controller/resource/kubernetes_resource.go:1479 +0x8cc
created by github.com/neuvector/neuvector/controller/resource.(*kubernetes).startWatchResource …
```

NVSHAS-8368 goroutine crash

---

agent/engine.go
agent/system.go

In most recent cases reported by customer, they all involved with istio-enabled POD whose parent pid==0, this is verified in support log such as following
"network_mode": "/proc/29013/ns/net",//sidecar
"network_mode": "/proc/29013/ns/net",//app container
"network_mode": "/var/run/netns/cni-e4e558af-a3ed-fa0a-9790-926ab564bea3",//parent
runtime is containerd
in our current setup we have both child's hasDatapath=true, during policy depolyment this can cause unexpected behavior, so only let service container's hasDatapath=true

NVSHAS-8406, only set service container's hasDatapath to true in istio case to avoid unexpected policy behavior

---

agent/bench.go
agent/engine.go
agent/group_profile.go
agent/service.go
agent/sniffer.go
agent/system.go
agent/task.go
agent/timer.go

We need to have a "read" lock protection of shared map data in the "gInfo" structure to keep it tightly only during the map search. This PR's improvement is focused on the map of the "gInfo.activeContainers".

Add rlock protection on the shared map, "activeContainers", access.

---

controller/kv/certmanager.go
controller/rest/rest.go

Change log level for `CheckAndRenewCerts() starts.` and `CheckAndRenewCerts() completes.` to debug.  
Also adjust cert recheck period to 30 minutes.

NVSHAS-8431 reduce log level for jwt cert manager

---

scripts/configure.sh
share/container/containerd.go
share/container/cri_client.go
share/container/crio.go
share/container/docker.go
share/container/dockerclient/dockerclient.go
share/container/types.go

This feature will allow the heterogeneous runtime engines (different runtimes on each node) with the same deployment.
(1) Remove the mounted runtime engine check from the "configure.sh".
(2) Enforcer: 
(a) Add an auto-select feature on the available runtime engine socket on the host
(b) Add a generic mounted engine socket for the enforcer to iterate all its supported runtime engines to find the suitable one.
```
For example:
volumeMounts:
- mountPath: /run/runtime.sock  <== predefined path name
name: runtime-sock
readOnly: false
volumes:
- name: runtime-sock
hostPath:
path: /var/run/k3s/containerd/containerd.sock   <== assigned socket path on the host 
```
(3) The original predefined mounted socket paths are still applied but they are looking up at the least priority.

NVSHAS-8436: Enforcer - automatic runtime engine selection

---

go.mod
go.sum
vendor/modules.txt

Dependabot reports a few vulnerabilities from gosaml2 after the previous PR is merged.
However, the gosaml2's version being used is https://github.com/holyspectral/gosaml2/commit/3d916621a704ea3f5580fa0a0a7b6a45502533e0, which is newer than v0.9.1 that dependabot recommends.  
A possible cause is that gosaml2's version in go.mod is generated as `v0.0.0-00010101000000-000000000000` and this caused a false positive in dependabot.  
This PR changes this version string to `v0.9.1`.  In my own fork, the issues on gosaml2 are not reported anymore.

NVSHAS-7616 dismiss false positive on dependabot

---

controller/controller.go
controller/resource/kubernetes_resource.go
share/container/stub.go
share/container/types.go
share/global/global.go

(1) Add a virtual (stub) runtime driver to handle the standalone controller cases( NOT pid==host environment) if there is no mounted runtime socket. 
(2) No mounted runtime socket is required on the k8s environment.
(3) It is backward compatible if the mounted runtime engine socket is still assigned (the runtime driver is used).
(4) For native docker/swarm, the mounted runtime engine socket is applicable.
(5) Not affecting the allinone (pid==host).

NVSHAS-8456: controllers: remove the mounting runtime socket requirement

---

controller/controller.go
share/container/containerd.go
share/container/crio.go
share/container/docker.go

Add a patch on the namespace function that failed with the empty node's name because there is no privileged mode of the controllers.

NVSHAS-8464: Not to run controller in privileged mode in kubernetes

---

agent/probe/fsn.go
agent/probe/incident_reporter.go
agent/probe/probe.go
share/scan/apps.go

Add package update incidents for the "java packages (jar, war, and ear)" file changes in a container. With the incidents, the controller would trigger a re-scan running container action if the "auto-scan" option is enabled.

NVSHAS-7917: Deleting vulnerable "java package" files doesn't remove from vulnerability list

---

agent/policy/network.go
agent/system.go

when toggle CTRL_EN_ICMP_POLICY env at controller, policy need to be pushed to dp once again

NVSHAS-8332, add additional fix to allow enable icmp policy enforcement

---

controller/controller.go
controller/kv/helper.go
controller/rest/auth.go
share/cluster/consul.go

This PR fixes https://github.com/neuvector/neuvector/issues/1118 and NVSHAS-8502.
Some users reported that after upgrade to 5.2.4 or 5.2.2-s1, they become unable to login NV console and receive empty authentication token from /auth API.
After checking consul kv, `/state/installation` is empty.
```
/ # consul kv get /state/installation
Error! No key exists at: state/installation
```
The ID is written in this line: 
https://github.com/neuvector/neuvector/blob/14751a0283320206642992c8e92283615e25b05b/controller/controller.go#L553C14-L553C31
However, no error is handled around that line.
After reviewing codes, a few possible causes were come up with:
1. The installation ID is not correctly initialized during fresh install.
2. No recovery mechanism
1. During fresh install, multiple controllers …

NVSHAS-8502 authentication token missing

---

agent/cluster.go

During a rolling upgrade of a multiple-controller setup, the enforcer could request admission on a phase-out old controller and can not detect the controller's leadership change. This situation leads to the enforcer's failure eventually.
This PR moves the leadership detection from a later procedure to help the admission request( grpc calls) with the most updated leader address and gain successful admission registrations.

NVSHAS-8432: un-managed node with "zombie" enforcer running

---

share/osutil/file_linux.go
share/osutil/file_linux_test.go

- The symlink in different mnt namespace sometime would escape the proc root by accident.
1. Resolve the symbolic link files under proc's root path by parsing the symlink, and make sure it doesn't escape the proc root by check the prefix of the resolved path
2. Add unit test to cover GetContainerRealFilePath function with following cases
- one layer of symlink
- abs path for symlink
- append another layer on type 1, make it a nest link
- circular link
- one node accidentally access to the circular link

[NVSHAS-8474] Resolve the symbolic link files under proc's root path

---

agent/cluster.go

Those events happened at the leaderChangeHAndler() when the bench worker was not initialized yet.

NVSHAS-8537 and NVSHAS-8538: goroutine crashes from leadChangeHandler()

---

share/osutil/file_linux.go
share/system/system_linux.go

- Fix find container's symbolic link with correct proc root by system.NewSystemTools().
- use docker.io/pohanhuangtw/allinone:procRoot to verify the code changes as allinone image, then check the log if there is unusual log.

NVSHAS-8532 Fix find container's symbolic link with correct proc root.

---

controller/rest/policy.go

Comparing two strings to the same case with `strings.ToUpper` is more computational expensive than `strings.EqualFold`.
Sample benchmark:
```go
func BenchmarkToUpper(b *testing.B) {
for i := 0; i < b.N; i++ {
if strings.ToUpper("any") != strings.ToUpper(api.PolicyPortAny) {
b.Fail()
}
}
}
func BenchmarkEqualFold(b *testing.B) {
for i := 0; i < b.N; i++ {
if !strings.EqualFold("any", api.PolicyPortAny) {
b.Fail()
}
}
}
```
Result:
```
goos: linux
goarch: amd64
pkg: github.com/neuvector/neuvector/controller/rest
cpu: AMD Ryzen 7 PRO 4750U with Radeon Graphics
BenchmarkToUpper-16      	 9510127	       141.6 ns/op	       6 B/op	       2 allocs/op
BenchmarkEqualFold-16    	286476537	         3.719 ns/op	       0 B/op	       0 allocs/op
PASS
ok  	github.com/neuvector/neuvector/controller/rest …
```

Compare strings with `strings.EqualFold`

---

controller/access/access.go
controller/api/apis.go
controller/api/apis.yaml
controller/cache/config.go
controller/remote_repository/export.go
controller/remote_repository/github.go
controller/rest/admission.go
controller/rest/compliance.go
controller/rest/crdsecurityrule.go
controller/rest/dlp_rule.go
controller/rest/remote_repository.go
controller/rest/rest.go
controller/rest/vulnerability.go
controller/rest/waf_rule.go
share/clus_apis.go
share/utils/nopcloser.go

These changes implement NVSHAS-8334 so that a user may export their CRD files directly to a configured remote repository. Currently GitHub is the only supported provider.
The export implementation is found in `controller/remote_repository/`.

NVSHAS-8334: Remote Repository Export

---

agent/policy/process.go

(1) Add allowed process rules after the NVSHAS-5999 change on the CIS benchmarks.
(2) Remove unnecessary rules.

NVSHAS-8560: unexpected NV.Protect incidents are found on stat command

---

controller/kv/cert.go
controller/kv/certmanager.go
controller/kv/certmanager_test.go
controller/kv/helper.go
controller/rest/auth.go
controller/rest/rest.go
controller/rest/server.go
go.mod
go.sum
share/auth/auth.go
vendor/modules.txt

NeuVector uses logrus custom formatter to print log messages.  This is done at below:
https://github.com/neuvector/neuvector/blob/315badd1e7b085485b8cf295b0e899ec63a3eb73/share/utils/utils.go#L857
However, when `%+v` is used, the error created by github.com/pkg/errors will print stacktrace, which is not desirable. 
Since go supports error-wrapping starting in 1.13, this PR removes github.com/pkg/errors and uses standard library for internal mapping.
1. Changed the RSA_KEYSIZE to `1` and observed error message.  Those errors are wrapped correctly.
```
2024-01-04T15:24:47.705|ERRO|CTL|kv.GenTlsKeyCert: failed to load ca key pair - error=open /etc/neuvector/certs/internal/adm_ca.cert: no such file or directory
2024-01-04T15:24:47.706|ERRO|CTL|kv.GenTlsCertWithCaAndStoreInKv: wrong cert/key - …
```

NVSHAS-8573 remove github.com/pkg/errors

---

controller/rest/system.go

No need to check the specific type of public key; relying on x509.ParseCertificate() should be sufficient as different signature algorithms have different types.

NVSHAS-8596-Invalid_Syslog_certificate

---

dp/dpi/dpi_entry.c
dp/dpi/dpi_msg.c
dp/dpi/parsers/dpi_http.c
dp/dpi/parsers/dpi_ssl.c

1. For strlcpy(), src must be Null-terminated string.
2. Add debug print to dump ip-fqdn storage map.

NVSHAS-8396: Fix strlcpy() without using Null-terminated string as src

---

controller/rest/bench.go

Since we add more message, we should remove this to avoid confusion
enforcer: [docker.io/pohanhuangtw/enforcer:8460](http://docker.io/pohanhuangtw/enforcer:8460)
controller: [docker.io/pohanhuangtw/controller:8460](http://docker.io/pohanhuangtw/controller:8460)
5.1.4 Minimize access to create pods - Review the users who have create access to pod objects in the Kubernetes API with the following command:
5.1.4 Minimize access to create pods

NVSHAS-8460 - Fix for UI showing in-complete message

---

controller/cache/automode.go
controller/cache/learn.go
controller/cache/log.go
controller/cache/sync.go

User reported that they saw repeated crashes with sigsegv in one controller and it can't be recovered automatically.  After running `kubectl rollout restart`, the issue is gone.  
After reviewing code, it's likely that the oldest/leader controller hit a race condition, which resulted in a corrupted audit event cache.
In this PR, proper protection is added to all slicers and maps, so these objects will not be corrupted.
Another check is also added in Rx side, so already corrupted data can be corrected.
Sanity test that includes:
1. Generate kube bench and container scan (audit)
2. Generate process events (incidents) and network events (violation)
3. Generate ICMP flood events (threat) 
4. Do rolling update and verifies these events still come back normal.
5. Verify container events using …

NVSHAS-8613 repeated sigsegv in one controller

---

agent/policy/process.go

NVSHAS-8622: unexpected NV.Protect incidents is found on support command

---

controller/controller.go

For testing purpose, we need to allow overriding controller image version info like we did for upgrade responder.

NVSHAS-8626: accepted alerts selection is not reset after rolling upgrade

---

controller/opa/opaIntegration.go

This MR disables the OPA telemetry by default by passing the "--disable-telemetry" flag as seen in the --help output of OPA:
```
./opa_linux_amd64_static run -h | grep tele
--disable-telemetry                    disables anonymous information reporting (see: https://www.openpolicyagent.org/docs/latest/privacy)
```
Fixes: #1184

Disable OPA telemetry by default

---

share/scan/scan_utils.go
share/scan/secrets/secrets.go

Patch a hole that we still scan the "hostPath" files from the k8s-mounted folders. Standalone allinone with the docker engine will not occur.

NVSHAS-8572: secrets/vul scanning engine does not ignore mounted files

---

controller/rest/bench.go

Since we add more message, we append all message to the desriptions.
controller: [docker.io/pohanhuangtw/controller:8678](http://docker.io/pohanhuangtw/controller:8678)
Before
5.1.4 Minimize access to create pods
After
5.1.4 Minimize access to create pods - Review the users who have create access to pod objects in the Kubernetes API with the following command:, rest of the messages.
https://github.com/neuvector/neuvector/pull/1162

NVSHAS-8678 - Fix for UI showing in-complete message

---

share/container/dockerclient/dockerclient.go

Upgrade docker API version to v1.24.

NVSHAS-8685: Scanner's docker client version 1.21 is deprecated and no longer supported

---

controller/cache/cache.go
controller/cache/group.go

In customer's case, there are more than 1500 empty groups schedule to be removed at the same time, when scheduled task expire, each task is executed with one goroutine, each task tries to AcquireLock which cause error message "Your IP is issuing too many concurrent connections, please rate limit your calls"
The solution is for each expired task only save group name to a groups slice, and 1 minute ticker is added to remove empty groups in batch, DeletePolicyByGroups and DeleteResponseRuleByGroups by groups also saves much more time than delete by single group

NVSHAS-8224, batch delete empty groups to improve auto removal performance

---

share/container/cri_client.go
share/container/crio.go
share/container/types.go

(1) Extending the current "crio" driver into the generic CRI driver
(2) Add "cri-dockerd.sock" into the auto-driver-detection sequence.

NVSHAS-8660: rke 1.25: runtime driver can not connect with the cri-dockerd.sock

---

share/scan/registry.go
share/scan/scan_cache.go
share/scan/scan_utils.go

Add utility functions on cacheable image information for the NeVector scanners. The scanner changes will be followed up later.
The two tiers of caches.
- base OS image layer data (compressed raw data files).
- scanned records, including secret scans, file maps, and layer package data (zipped JSON files). 
About 54% of the scanning time could be shortened if the  "repeated" scanning (or different databases) or same base OS images often occur.
Note:  For the critical section among the multiple scannerTasks instances, the (Unix) FileLock is implemented.

NVSHAS-7664: Help reduce ISP data charges when performing registry scanning

---

agent/agent.go
agent/agent_linux.go
agent/engine.go
agent/probe/intf.go
agent/probe/intf_linux.go
agent/probe/types.go
share/system/sidekick/net_linux.go

1. Use netlink.LinkSubscribe() and netlink.AddrSubscribe() to monitor link and ip address changes
2. Add cache for link state and host ips to do comparison
3. Move Host i/f change monitoring from Probe to engine.go

NVSHAS-5391 & 8631 Improve Host i/f update monitoring

---

share/container/dockerclient/dockerclient.go

A temporary workaround. Need to sync it to the scanner.

NVSHAS-8716: Newer scanner error for local image and produce inaccurate scanning results

---

share/container/dockerclient/dockerclient.go

Reverse the PR#1219 and keep the docker API at the v1.24. Need to solve the scanner issue at NVSHAS-8718.

NVSHAS-8716: reverse API version change

---

agent/probe/probe.go
agent/probe/process.go

Some Java pods repackage their jar package by putting some individual jars in a temporary folder. We need to filter out those events during the pod creation.

NVSHAS-8736: unexpected jar package alert from pod deployment

---

controller/rest/sigstore.go

Even though the back-end behavior is not affected by both fields being true, this was causing issues with the UI after having created a root of trust.

NVSHAS-8812: rootlessKeypairsOnly overrides isPrivate

---

share/scan/apps.go

Allows for multiple declared entries in manifest.mf and prefers Bundle-Name over Bundle-SymbolicName. Deprecated tomcat case removed.

NVSHAS-8730 allow parsing multiple entries from manifest.mf

---

agent/grpc.go
agent/workerlet/pathWalker/pathWalker.go
agent/workerlet/types.go
share/scan/scan_utils.go

The target container is privileged with the "pidHost" attribute. We need to adjust the base OS identification method,

NVSHAS-8741: NeuVector scan shows inconsistent baseos image

---

controller/rest/registry_kits.go
controller/scan/image.go

Small changes, hard to find.
When running a registry test, the proxy information will now be used conditionally, based on the `use proxy` setting.
Also, when updating a registry, the proxy information will be updated correctly.

NVSHAS-7145: correct proxy update

---

dp/dpi/parsers/dpi_sqlinjection.c

1. add a whitespace after "exec" to resolve potential false positive detection
2. simplify case insensitive check for keywoards
3. improve "union" and "or" detection to cover more SQLi cases.

NVSHAS-8886: Fix SQLi detection for "exec" statement

---

share/cluster/grpc.go

In the previous version, `cancel()` is called when leaving `newClient()`.  However, it should be called in `s.cancel()` instead in most of cases.
This PR fixes the issue.

fix: do not call cancel in all path in newClient()

---

agent/engine.go
agent/policy/network.go

when see container with multiple i/f and at least one of them in non-veth type, we cannot use default veth bridge for protect mode, we will use netfilter_queue for this container.

NVSHAS-8486, to support multinetwork container with additional non-veth interface

---

share/container/docker.go

The "RepoDigests" filter in the docker driver should not ignore the matching base element. It causes a missing "Digest" like the below Repo representations with the same tag:
```
index.docker.io/library/redis
library/redis
docker.io/redis
```

NVSHAS-8952: the digest info is missing in local image scan

---

share/scan/registry/tokentransport.go
share/scan/registry/tokentransport_test.go

When docker hub's token service is called too many times, backend would start throttling and return 429 too many requests. 
When this happens, the response from the token service will not be closed and cause memory leak gradually.  This PR fixes the issue.
While writing unit-test, it was found that the second request's error will always be nil due to the err variable is shadowed.  This issue is also fixed and covered in unit tests.

fix: NVSHAS-8968 resp.Body is not closed

---

controller/cache/cache.go
controller/cache/group.go
controller/cache/object.go
controller/resource/kubernetes_resource.go
controller/resource/types.go

K8s: the latest runtime will not report the privilege flags of the containers. We need to retrieve this information from k8s pod data.
(1) k8s pod data: collecting container data slices.
(2) Update the privilege flag when the controller receives the first reported workload data.

NVSHAS-8973: the value of .workloads[].privileged is incorrect in rke clusters with cri-dockerd runtime

---

share/scan/apps.go
share/scan/scan_utils.go

dotNet package parser:
(1) Reduce the duplicate package dependency from the same package manifest file.
(2) Not allowed repeated searching on an app package scan.
(3) DotNetCore version correction.

NVSHAS-9026: dup and missing .NET module name

---

share/container/crio.go

Add runtime handler process name.

NVSHAS-9028: unexpected NV.Protect incidents is found on crio-conmon command in k8s with crio runtime

---

share/fsmon/monitor.go

Some identification system files will be modified during their runtime container creations. Somehow they were deployed late and we think they were false-positive incidents. Add a time filter to avoid unnecessary events.

NVSHAS-8873: suspected false positive alerts on /etc/hosts modified

---

agent/engine.go
agent/group_profile.go
agent/system.go
share/fsmon/monitor.go

Differ workload update and leave cases to avoid the timer resets.

NVSHAS-9061: the 60-second timer is reset after adding new file rules

---

share/cluster/consul.go

This PR is for 5.4. 
Remove 3DES cipher suites from consul RPC port 18300.  Verified with upgrade from helm 2.4.0 (NV 5.1.0).
After fix:
```
PORT      STATE SERVICE     VERSION
18300/tcp open  ssl/unknown
| ssl-enum-ciphers: 
|   TLSv1.2: 
|     ciphers: 
|       TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (secp256r1) - A
|       TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (secp256r1) - A
|       TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA (secp256r1) - A
|       TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA (secp256r1) - A
|       TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 (secp256r1) - A
|     compressors: 
|       NULL
|     cipher preference: server
|     warnings: 
|       Key exchange (secp256r1) of lower strength than certificate key
|   TLSv1.3: 
|     ciphers: 
|       TLS_AKE_WITH_AES_128_GCM_SHA256 (ecdh_x25519) - …
```

NVSHAS-9037 remove 3DES cipher suites

---

share/scan/scan_utils.go

Container scans: Remove "/tmp" and "/bin" from the skipped paths.

NVSHAS-9071: some modules are not reported in the container scan only

---

agent/probe/faccess_linux.go
agent/probe/process.go

Add patch after dev54 merged into main.
The not-listed (learned) process during the Protect mode will be blocked as dangerous processes.

NVSHAS-6740: Improvement of zero-drift baseline profile

---

agent/agent.go

By default port 18500 shouldn't be open for enforcer and allinone.  Also verified that controller, scanner and registry-adapter don't have this issue.

fix: NVSHAS-9108 port 18500 shouldn't be open

---

agent/probe/probe.go

The container's file-changed monitor is not initialized when the process profile is disabled. We have a major enhance on the NV Protect on the v5.4.
NV Protect is always on even if the the process profile is disabled.

NVSHAS-9119: goroutine crash at probe.(*FileNotificationCtr).AddContainer()

---

controller/cache/learn.go

This fix is to resolve following error
Panic condition:
fatal error: concurrent map iteration and map write
goroutine 946 [running]:
runtime.throw(0x2d2b27e, 0x26)
/usr/local/go/src/runtime/panic.go:1116 +0x72 fp=0xc0a6b9a1d8 sp=0xc0a6b9a1a8 pc=0xdd9c02
runtime.mapiternext(0xc0a6b9a300)
/usr/local/go/src/runtime/map.go:853 +0x552 fp=0xc0a6b9a258 sp=0xc0a6b9a1d8 pc=0xdb49a2
github.com/neuvector/neuvector/controller/cache.unlearnAll(0xc05adf5420, 0x15)
/go/src/github.com/neuvector/neuvector/controller/cache/learn.go:708 +0x92 fp=0xc0a6b9a480 sp=0xc0a6b9a258 pc=0x24e94f2
github.com/neuvector/neuvector/controller/cache.cbDeleteNode(0xc05adf5420, 0x15)
/go/src/github.com/neuvector/neuvector/controller/cache/learn.go:1189 +0x6f fp=0xc0a6b9a4b8 sp=0xc0a6b9a480 pc=0x24eff2f …

NVSHAS-9076, resolve concurrent map iteration and map write on lprWrapperMap

---

agent/policy/process.go
agent/probe/process.go

Add NV Protect into the zero-drift baseline profile.

NVSHAS-9129: unexpected NV.Protect incidents is found on grep command

---

agent/engine.go
agent/group_profile.go
agent/probe/process.go
share/container/docker.go
share/container/dockerclient/types.go
share/container/types.go

The health check commands of the docker containers had been treated as false-positive external intruder process incidents .
This PR is going to neglect those health check commands on the docker native systems. First, it identifies the health check commands from the container runtime data.

NVSHAS-9124: docker: many unexpected healthcheck processes incidents are reported

---

agent/probe/fsn.go

Add allinone ("controller+enforcer+manager") type image into the FSN filter.

NVSHAS-9161: unexpected Container.FileAccess.Violation incidents are found after a specific container is started

---

controller/cache/log.go
controller/cache/response.go
controller/common/output.go
controller/kv/create.go

1. Ability to include comment of response rule in alert content and beautify content
2. output the data result like the following (slack, Json, txt as example)
3. Beautify by move the rule to the front of the messages if user setup any. (if they don't specify, we don't provide the response rule comment.)

[NVSHAS-6979] Ability to include comment of response rule in alert content and beautify content

---

agent/engine.go

Set up a timer to call taskReexamHostIntf after 1 minute of enforcer startup to avoid missing network interfaces if there is no host link or address change

NVSHAS-9177: Reexam host interface afte 1 minute of enforcer startup

---

share/migration/migration_informer.go
upgrader/main.go
upgrader/postsync.go
upgrader/presync.go

This PR addresses three issues:
1. Allow disabling rotation via an environment variable.
2. Read namespace from /var/run/secrets/kubernetes.io/serviceaccount/namespace.
3. NVSHAS-9150 do not panic when lease is absent

feat: NVSHAS-7518 internal cert rotation

---

agent/probe/fsn.go

Avoid to monitor the allinone log files.

NVSHAS-9208: keep repeating a specific log entry in fedora os 40

---

controller/grpc.go

This flag needs to be set to true for the scanner to not downgrade critical CVEs when the controller supports them.
Related scanner code for reference: https://github.com/neuvector/scanner/blob/86b0b95c33d80f74cf4a089aef2b499939fedcad/server.go#L366

NVSHAS-8242: update critical vul support flag

---

agent/engine.go

When link state is updated, use "OperState==netlink.OperUp" to check if link needs to be updated or not.

NVSHAS-9019: Fix unsynchronized link state for host interface

---

controller/nvk8sapi/nvvalidatewebhookcfg/admission/admission.go
share/scan/scan_report.go
share/types.go

This temporarily nullifies any effectual or front-facing logic/types for the critical CVE change.

NVSHAS-9223: temporarily revert critical cve logic

---

controller/resource/kubernetes_resource.go

Per https://github.com/kubernetes/client-go/issues/623, watch API will close the connection when no event is detected in a given time frame.
When this happens, io.EOF will be returned and cause noises in controller log.
This PR makes io.EOF not reported to state callback.
- Install NV and monitor controller's logs => no `OrchConnLastError:EOF`.
- Use tcpkill to terminate API service connection => connection can be recovered with correct error logs:
```
2024-07-25T02:51:45.312|INFO|CTL|main.(*orchConn).cbWatcherState: updating conn status - lastError=read tcp 192.168.36.233:57276->10.100.0.1:443: read: connection reset by peer status=disconnected
2024-07-25T02:51:45.321|INFO|CTL|main.(*orchConn).cbWatcherState: updating conn status - lastError=read frame body: read tcp …
```

fix: NVSHAS-8439 ignore io.EOF from k8s watch api

---

controller/rest/auth.go
controller/rest/federation.go
controller/rest/system.go
share/clus_apis.go

When a user log in NV console, an alert message is generated 
1. if a managed cluster is disconnected for > 1 hour (when user is on primary cluster UI)
2. if the primary cluster is disconnected for > 1 hour (when user is on managed cluster UI)
There is another UI jira case so that user can accept this alert so that this alert won't show up in 1 hour.
After 1 hour, if the disconnection still persist, the alert is re-generated in user's next login.
The 1 hour value can be overridden by env var specified in controller deployment yaml:
```
- name: TELEMETRY_FREQ
value: "3"   // minutes
```

NVSHAS-8925: Log/Alert when Federated cluster disconnects

---

controller/cache/cache.go
controller/cache/cert.go
controller/controller.go
controller/kv/certmanager.go
controller/rest/rest.go
share/clus_apis.go

Auto-generate TLS certificate when `/etc/neuvector/certs/ssl-cert.*` is absent, so we can remove built-in TLS certificates from container images.
1. Auto generate TLS certificate used by REST server and store in consul kv when `/etc/neuvector/certs/ssl-cert.pem` or `/etc/neuvector/certs/ssl-cert.key` doesn't exist.
2. The auto-generated certificate will also be used by federal REST server when `fed-ssl-cert` and `ssl-cert` are both absent.
3. Provide a notification mechanism via consul kv watch to minimize the time period when the certificate is different across different nodes.
4. Fix a minor issue in lock. 
The example of the TLS certificate is as below:
```
Certificate:
Data:
Version: 3 (0x2)
Serial Number: 2029 (0x7ed)
Signature Algorithm: sha256WithRSAEncryption
Issuer: C = US, ST = …
```

NVSHAS-8305 remove built-in certificate

---

controller/rest/rest.go
controller/rest/servererrorlogger.go

When controller's service is configured as LoadBalancer, LoadBalancer can perform health check on the endpoint and generate a lot of error messages in controller:
```
http: TLS handshake error from xxxxxx: EOF
```
This commit skips this kind of error by providing a different logger for controller's REST server.

NVSHAS-7853 TLS handshake EOF

---

controller/api/apis.go
controller/api/apis.yaml
controller/rest/system.go

Controller doesn't check if password is null or not before overwriting the existing value.
This commit provides an API update for UI to
resolve this issue.
Slack integration with tinyproxy.

NVSHAS-8539 proxy password lost

---

agent/probe/faccess_linux.go
agent/probe/probe.go
agent/probe/process.go

Patching the insider process conditions to allow the actions when a not-learned (user-defined) process rule is applied to the modified/newly-added app.

NVSHAS-9290: User added process profile rule not taking effect with ZD enabled

---

controller/api/apis.yaml

I'm getting a lot of this warning when pushing into my fork:
```
remote: - GITHUB PUSH PROTECTION
remote:   —————————————————————————————————————————
remote:     Resolve the following violations before pushing again
remote: 
remote:     - Push cannot contain secrets
```
This commit removes the invalid AWS keys which trigger the alerts.

fix: remove AWS keys in API docs

---

agent/agent.go
controller/controller.go
controller/resource/kubernetes_rbac.go
controller/resource/kubernetes_resource.go
share/k8sutils/k8sutils.go
share/k8sutils/permissions.go
share/migration/migration_informer.go
upgrader/postsync.go
upgrader/presync.go

This PR contains two parts of changes:
It's possible that users have out-of-date RBAC settings in their environment, for example, these settings are maintained by other team.  Without proper RBAC settings, NV components can fail to start.
This commit fixes the issue by checking required RBAC permission and falling back if the check fails.
When the resources are missing, controller will remind users by generating alerts.

fix: NVSHAS-9289 allow upgrade when RBAC missed

---

agent/agent.go
controller/cache/compliance.go
monitor/monitor.c

1. Fix Ingress Egress esposure shows 0 Vulnerabilities
2. Rename AGE_SYSLOG_LEVEL to ENF_SYSLOG_LEVEL to make naming consistent

NVSHAS-9292: Fix Ingress Egress esposure shows 0 Vulnerabilities

---

Makefile
agent/bench.go
agent/nvbench/journal.tmpl
agent/nvbench/kube_runner.tmpl
agent/nvbench/kubernetes-cis-benchmark/cis-1.24/master/1_control_plane_components.yaml
agent/nvbench/kubernetes-cis-benchmark/cis-1.6.0/master/1_control_plane_components.yaml
agent/nvbench/kubernetes-cis-benchmark/cis-1.8.0/master/1_control_plane_components.yaml
agent/nvbench/kubernetes-cis-benchmark/cis-k3s-1.8.0/master/1_control_plane_components.yaml
agent/nvbench/kubernetes-cis-benchmark/cis-k3s-1.8.0/master/2_etcd.yaml
agent/nvbench/kubernetes-cis-benchmark/cis-k3s-1.8.0/master/3_control_plane_configuration.yaml
agent/nvbench/kubernetes-cis-benchmark/cis-k3s-1.8.0/master/5_policies.yaml
agent/nvbench/kubernetes-cis-benchmark/cis-k3s-1.8.0/worker/4_worker_nodes.yaml
agent/nvbench/utils/utils.sh
agent/probe/process.go
agent/probe/process_linux.go
share/scan/compliance.go

CIS benchmark is not support k3s before.
- support CIS benchmark k3s
- Read the journalctl for the command processing. (use nstools)
- add `isKubeProcess` to detect the executable of k3s not proc name, since the proc name could change over time, and I keep the original logic for backward compatible.
Set up the k3s env, and make sure the other env works as well.

[NVSHAS-9270] Support k3s for cis benchmark pipeline

---

share/migration/migration_informer.go

In the previous version, annotation changes get ignored, which lead to these components wait indefinitely if annotation is the only part changed.
This commit fixes the issue by not ignoring the annotation change.

fix: NVSHAS-9336 secret controller not work

---

share/migration/migration_informer.go

This happens when a secret is being updated and a NV component is starting. In this case, NV component could read an empty internal secret, which is as expected.  However, the current logic doesn't ignore this secret correctly, hence the issue.
This commit makes sure that informer will wait until certificate is available in the secret.

fix: NVSHAS-9342 controller failed to load secret

---

agent/agent.go
agent/engine.go
agent/probe/probe.go
agent/probe/process.go
agent/task.go
controller/api/apis.go
controller/cache/cache.go
controller/cache/config.go
controller/common/common.go
controller/controller.go
controller/rest/device.go
monitor/monitor.c
share/clus_apis.go
share/cluster/intfs.go
share/fsmon/monitor.go

1. Rename shared variables with enforcer & controller
2. Introduce "error", "warn", "info", "debug" level for config via helm & runtime

NVSHAS-7687 & 9006: Redesign LogLevel setting in enforcer and controller

---

share/scan/registry.go

This makes the scan logs more understandable, by reducing unnecessary paths and adding verbosity to certain logical forks.
This also fixes the signature image info retrieval from spamming both the registry test and the scan logs, previously when finding all the images to scan for a registry/repo, the signature images would be considered regular images, and thus the controller would attempt to fetch the "signature's signature", resulting in a flood of "not found" errors.

improve scan logs & stop recursive signature fetching

---

share/scan/registry/registry.go

In the previous version, proxy setting is incorrectly derived from wrong fields.  This commit fixes the issue.

fix: NVSHAS-9358 image scan using proxy would fail

---

upgrader/postsync.go
upgrader/presync.go

In one of the previous changes, POD_NAMESPACE environment is removed from cert-upgrader.  This leads to not being able to get the correct namespace when running in a non-default namespace, e.g., `cattle-system`.
This PR fixes the issue by getting namespace from service account folder.

fix: NVSHAS-9387 get namespace from k8s token

---

share/global/global.go

Add docker as platform default, or it will return "" when the platform is docker.
1. check the platform will be empty in current build
2. check the platform will be correct in custom build

[NVSHAS-9393] Add init platform for docker in getPlatform

---

share/scan/compliance.go
share/scan/compliance_test.go

- not to remove prime to make sure the user is able to see the prime data

[NVSHAS-8799] Not to remove the prime yaml

---

agent/policy/process.go

Eliminate the false-positive during the rolling upgrades.

NV Protect: backward compatible for k8s readiness

---

go.mod
go.sum
vendor/github.com/docker/docker/AUTHORS
vendor/github.com/docker/docker/api/types/registry/registry.go
vendor/modules.txt

Upgrade docker's vendor package to v26.1.5

CVE-2024-41110: Upgrade docker package

---

agent/engine.go
agent/probe/process.go

(1) Except for enforcers, other NV containers can not block not-allowed commands because of the invalid rootPid information. Fill the data and it works.
(2) Reduce unnecessary traces

NVSHAS-9325: NVProtect: Manager/Controller is not blocking not-allowed commands 

---

upgrader/main.go

ArgoCD doesn't support creating lease object per
https://github.com/argoproj/argo-cd/issues/12722
This change will enable k8slock to try to create lease object when the lease object is absent.

fix: NVSHAS-9442 create lease object for ArgoCD

---

share/utils/version.go

Add function to compare package versions ignoring epoch to avoid changing function parameters of base Compare function.

NVSHAS-9436 add CompareWithoutEpoch function

---

.golangci.yml

exclude reports for NV's json tag extension

NVSHAS-9525: Resolve existing Go linter issues

---

controller/rest/rest.go
controller/rest/rest_test.go

This PR will allow configuring non-https URL for default registry used in admission control rules evaluation.
When the container image specified in a pod spec doesn't contain the registry, for example:
```
spec:
containers:
- name: iperfserver
image: iperf
```
NV controller uses the following 4 registries to find the scan result of the image:
```
https://docker.io/
https://index.docker.io/
https://registry.hub.docker.com/
https://registry-1.docker.io/
```
If user wants to use different registries as the default registries for admission control rule evaluation, they can specify an env var in NV controller deployment like:
```
env:
- name: CTRL_SEARCH_REGISTRIES
value: "http://myregistry1.net,https://myregistry2.net"
```
However, the logic in NV 5.4 doesn't support http scheme in the value. …

NVSHAS-9532: The image scan is completed but deployment is still not allowed

---

controller/rest/repository.go

- Clear password field for registry data when user use controller mode with Jenkins to scan
Run the jenkins with controller, make sure no password in it.

[NVSHAS-9576] Clear password field for registry data when user use controller mode with Jenkins to scan

---

share/system/system_linux.go

The ReadCmdLine() failed because it did not fetch the line.

ReadCmdLine failure: Fix golint PR error.

---

agent/engine.go
agent/pipe/port.go

Container has vxlan setup, in protect mode if we split veth interface into veth bridge the vxlan setup will be affected, so we use nfq(iptable rules) instead in this scenario.

NVSHAS-9425: create nfq when container has vxlan 

---

db/assetvuls.go

The full name displayed in the UI is made up of two separate fields (specifically, name and tag). 
The backend needs to take this into account when performing quick filter search.

NVSHAS-9571 fix image asset advanced filter issue

---

controller/cache/federation.go

Reason: managed clusters' REST version is not stored in primary cluster's cache

NVSHAS-9589: Managed clusters disconnected - Version mismatch with primary cluster

---

.github/workflows/golangci-lint.yml

When there are more than 20,000 lines in GitHub diff, GitHub will return 406 error and prevent linter from running correctly.
This commit uses `new-from-rev`, so it can generate diff from git repo instead of GitHub API.
Related issue:
https://github.com/golangci/golangci-lint-action/issues/996

fix: linter: use new-from-rev

---

controller/rest/crdsecurityrule.go
controller/rest/group.go
controller/rest/system.go
share/types.go

Export group with invalid policy/profile mode value is wrongly allowed
Use a shared function to validate the policy/profile mode values
Also remove license check for configuring Protect mode

NVSHAS-9605: Export group with invalid policy mode & process profile mode values is mistakenly allowed

---

share/cluster/grpc.go

The default "rx" grpc packet size of a client at controller is 4MB but the remote scanner grpc server TX is not set and its default 4GB. When the server send response over 4MB (6MB in this case), the client failed it. 
Current solution is to set the packet sizes of both directions as 20MB. If we hit the limit again, it needs to evaluate the performance on the bigger packet sizes or make chunks between two endpoints.

NVSHAS-9608:grpc client failed to rx > 4MB pkt

---

controller/cache/admission.go
controller/cache/admission_test.go
controller/rest/admission.go

consolidate rule criteria that have the same name and operator(containsAny/notContainsAny). 
ex:
criteria: image notContainsAny {controller}, image notContainsAny {manager} 
is merged to: 
criteria: image notContainsAny {controller, manager}

NVSHAS-9534: Display error in admission controls

---

share/osutil/process_linux.go

All of getConnectionByFile errors are for reference purpose. The process might be done before it obtains the file. It is normal. They should be assigned to DEBUG level.

NVSHAS-9631: Reduce some enforcer errors

---

share/cluster/consul.go

Remove TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 from Tls_cipher_suites to support consul 1.20.1

NVSHAS-9539: Update Tls_cipher_suites for consul 1.20.1

---

controller/scan/image.go

It is because Get(https://quay.io/v2/) always return 401 that we should not always treat it as failure

NVSHAS-9651: Quay.io needs user name and password for scanning

---

controller/scan/jfrog.go
share/scan/registry/tags.go

- The old API for fetching JFrog resources encounters issues with the newer jfrog version.
- Created a backup function specifically for handling JFrog tag retrieval.
- Ensures compatibility with JFrog's updated API while preserving existing registry functionality.
- repository scan with jfrog
- reposiorty scan with docker

[NVSHAS-9507] Fix JFrog fetch tag issue.

---

share/scan/apps.go
share/scan/apps_test.go

parseDotNetPackage did not properly handle deps.json format, causing it generate a .Net entry that would never match and additionally miss several target entries.

NVSHAS-9142 fixed issues with parseDotNetPackage

---

upgrader/main.go

Do not check the lease object's presence, so it can be created correctly on ArgoCD.

fix: NVSHAS-9443 ArgoCD issue

---

share/container/docker.go

- docker has longer timeout, thus removing the shorter timeout

[NVSHAS-9683] docker has longer timeout

---

controller/api/apis.yaml

Based on the API definition in `controller/api/apis.go`, `remote_permissions` is not a property of `RESTUser`.
As it does not exist in the actual API, I think it makes sense to remove it from the Swagger documentation.

Remove unused property remote_permissions in Swagger documentation of RESTUser

---

controller/access/access.go
controller/access/access_test.go

It sets the required permission for calling GET(v1/system/score/metrics)

NVSHAS-9669: Overall security score through REST API

---

agent/probe/process.go

The reported process incident should not be learned even it changes its process name on the same pid.

NVSHAS-9653: learning wrong process rules

---

controller/grpc.go

- The previous size of 128 was insufficient, causing timeouts during scanner registration with the controller.

[NVSHAS-9681] Scanner Registration Timeout Issue: Increased database slots from 256 to 512.

---

controller/cache/scan.go
controller/rest/vulasset.go
db/assetvuls.go

The asset policy mode data could become stale when accessing the risk page.
This change ensures the latest data is fetched from the cache while composing the risk page.

NVSHAS-9696: Inconsistent colour indication of assets on risk page

---

share/cluster/consul.go

The previous [PR](https://github.com/neuvector/neuvector/pull/1701) has wrong target branch specified: 
This PR ported the change from https://github.com/neuvector/neuvector/pull/1697#pullrequestreview-2501086890 to 5.4.2.

fix: NVSHAS-9705 disable consul gRPC server

---

monitor/monitor.c

Reverts neuvector/neuvector#1719
@alopez-suse It is a wrong repo to check in. You should put it in the scanner repo.

Revert "NVSHAS-9726: add scanner proxy url flag to monitor fork exec"

---

agent/probe/incident_reporter.go

Enforcer: replace the insecure cryptography (MD5) with the SHA-256

NVSHAS-9752: replace md5 keys by sha256

---

agent/probe/faccess_linux.go
agent/probe/process.go
share/clus_apis.go

Backported:
(1) During Monitor mode, set alerts on not listed family processes. 
(2) Add process violation messages on above incidents

NVSHAS-9751: add not-listed family process rule alert

---

.github/workflows/golangci-lint.yml
.github/workflows/unitest.yaml

`pcre.h` is missing due to GitHub's recent change to move from ubuntu 22.04 to ubuntu 24.04 in ubuntu-latest runner.  For example, [this run](https://github.com/neuvector/neuvector/actions/runs/12750162538/job/35534278327?pr=1722).
This PR installs `libpcre3-dev` so unit test can run without problem.

fix: allow ut to run with ubuntu-latest runner

---

controller/common/output.go

Root cause: 'level' field already exists in the embedded type LogCommon

NVSHAS-9777: Webhook JSON with duplicated 'level' keys

---

controller/api/apis.go
controller/api/apis.yaml
controller/cache/compliance.go
controller/cache/connect.go

1. Add LastSeenAt timestamp in RESTConversationReportEntry from connection report
2. Remove the timestamp in RESTRiskScoreMetrics as customer doesn't need it for snapshot

NVSHAS-9759: Add timestamp in RESTConversationReportEntry

---

package/build_controller.sh

Remove nstools from controller given that controller doesn't have required permissions to use it.

fix: remove nstools

---

agent/probe/fsn.go
agent/workerlet/pathWalker/pathWalker.go
agent/workerlet/types.go
share/fsmon/monitor.go
share/fsmon/monitor_test.go
share/osutil/file_linux.go

This change aims to improve the performance of the file monitor by reducing its CPU and I/O overhead
(1) Initial Flat Scan: Will perform a one-time "flat scan" to identify all relevant files within the workload's scope. This eliminates the need for constant directory traversal, significantly reducing I/O operations.
(2) Limited the number of concurrent "worklets" used by the file monitor will be limited to two. This controlled concurrency prevents excessive resource consumption and potential performance bottlenecks.
(3) Optimized "worklet" Scope:  Worklet efficiency will be improved by defining specific folders for each worklet to monitor.

NVSHAS-9756: File Monitor Performance Optimization

---

share/scan/registry/manifest.go

- Append header to support the OCI format of a manifest. 
The current implementation will call the following for any jfrog build when scanning
```bash
curl -u usr:pwd\
-H "Accept: application/vnd.docker.distribution.manifest.v2+json" \
https://nvdebug.jfrog.io/v2/{repo}/{image}/manifests/{tag}
```
But the header is always, this header is compatible with Docker V2 image manifests.
```bash
application/vnd.docker.distribution.manifest.v2+json 
```
However, to support OCI-compliant images (e.g., OCI build images), the header must also accept:
```bash
application/vnd.oci.image.manifest.v1+json 
```
Thus we use consigned-image as fallback function to work with it

[NVSHAS-9784] NV returning 404 during Jfrog image repository scanning

---

CODEOWNERS

Update CODEOWNERS, so no owners are assigned to the files under root, e.g., `/go.mod` and `vendor/`.  Updating these files still require a PR approval.

chore: update CODEOWNERS to skip files under root

---

.github/workflows/golangci-lint.yml

1.24 is causing issues in lint.  This is a temporary fix to re-enable golangci-lint.

chore: pin golang version used in lint

---

share/cluster/grpc.go

The gRPC connection used in `IsEnforcerGRPCCommpressed()` and `IsControllerGRPCCommpressed()` is not closed properly.   This usually won't cause problem, unless the connection becomes unstable.
This commit fixes the issue by closing the connection.

fix: NVSHAS-9823 goroutine leak

---

agent/probe/faccess_linux.go
share/fsmon/fanotify_linux.go
share/fsmon/inotify_linux.go
share/fsmon/monitor.go

It ignores the errors when the target files were removed.

NVSHAS-9824: reduce error messages when the file monitor exited

---

controller/api/apis.go
controller/api/apis.yaml
controller/cache/log.go
controller/cache/object.go
controller/cache/scan.go
controller/rest/configmap.go
controller/rest/scanner.go
share/clus_apis.go

- Support auto scan with fine-grained level control.
- Auto-scan can be configured globally or with fine-grained control for workloads, hosts, or platforms. However, if any of the detailed control fields (enable_auto_scan_workload, enable_auto_scan_host, or enable_auto_scan_platform) is set to false, auto-scan will be disabled overall, because these flags collectively represent a "scan all" setting.
- set auto-scan through patch /v1/scan/config, will not affect enable_auto_scan_workload, enable_auto_scan_host, or enable_auto_scan_platform
- if set any of enable_auto_scan_workload, enable_auto_scan_host, or enable_auto_scan_platform, it will follow the following _**if enable_auto_scan_workload, enable_auto_scan_host, or enable_auto_scan_platform is set to false, auto-scan will be disabled …

[NVSHAS-9826] Support auto scan with fine-grained leverl control.

---

agent/probe/process.go

Patch the NV Protect at process monitor side.

NV9842: Enforcer- Unable to access manager CLI

---

controller/controller.go

- move the init NewScanCreditManager up, ensure NewScanCreditManager is not nil
- The issue occurs because scanCreditMgr is initialized too late, leading to a nil pointer dereference.

[NVSHAS-9853] Fix nil ScanCreditMgr issue

---

agent/dp/ctrl.go
agent/pipe/port.go
agent/policy/network.go
agent/probe/probe.go
agent/probe/process_linux.go
controller/cache/admission.go
controller/cache/learn.go
controller/nvk8sapi/nvvalidatewebhookcfg/nvvalidatewebhookcfg.go
controller/rest/admwebhook.go
controller/scan/registry.go
share/cluster/grpc.go
share/cluster/intfs.go
share/container/cri_client.go
share/fsmon/monitor.go
share/osutil/process_linux.go

So far we've fixed most of issues reported by golangci-lint.  These are the remaining ones.  
```
S1009: should omit nil check; len() for nil slices is defined as zero (gosimple)
SA1015: using time.Tick leaks the underlying ticker, consider using it only in endless functions, tests and the main package, and use time.NewTicker here (staticcheck)
SA1019: grpc.DialContext is deprecated: use NewClient instead.  Will be supported throughout 1.x. (staticcheck)
```
For SA1015, our usage is reviewed to make sure our usage is alright - no ticker leak.
For SA1019, because gRPC won't deprecate those APIs until its next major version, these findings are marked as nolint. 
After this PR, we don't have to run golangci-lint against only diff anymore.  This will help us to discover more issues using …

fix: staticcheck and gosimple findings

---

share/container/types.go

The latest rke2 replaces its "kubelet" running parameters which cause the mismatched case with "docker" runtime together on the same node. 
Other work-arounds:
(1) User can use HELM's "k3s" flag to override the runtime driver 
(2) Remove the docker runtime from the nodes.

NVSHAS-9876: Enforcer crashed on rke2 v1.32

---

package/Dockerfile.controller
package/Dockerfile.enforcer

In 5.4.2, the version format in golang space missed a v prefix.  This commit fixed the issue.

fix: incorrect version format

---

agent/agent.go
agent/engine.go
agent/probe/probe.go
agent/probe/process.go
agent/probe/types.go
share/fsmon/monitor.go

(1) Avoid the false-positive runtime processes prevention on nv pods. 
(2) Identify correct nv pod roles
(3) Reduce file events on the not-modified files

NVSHAS-9828: fix false-positive asynchronous processes checkup

---

agent/policy/process.go

The situation is unlikey occured because of the downstream profile data is at least 5-7 sec apart. However, it good to make the prevetion.

Potential race condition

---

agent/probe/process.go

On k8s, controllers have setup k8s PROBE actions. They are allowed but we failed to identify it on a very short-lived action.

NV9894: false-positive incidents on k8s's controller

---

agent/grpc.go
agent/workerlet/pathWalker/pathWalker.go
agent/workerlet/types.go
share/scan/apps.go
share/scan/scan_utils.go

K8s only: add returning image repo into the scan data. Later on, the scanner can utilize the information to match its cve database.
Add new module type and its associated structure:
```
Kubernetes = "kubernetes"
const (
TypeK8sRepo = "k8sRepo"
)
type KubernetesResource struct {
ResourceType string `json:"type"`
Name         string `json:"name"`
}
```

NV9905: k8s workload scan returns image metadata

---

agent/probe/process.go

k8s docker-specific: the parent of the monitor becomes systemd

NV9919: Enforcer keep crashing because monitor getting killed

---

controller/api/apis.yaml

The API documentation for the endpoint `/v1/assess/admission/rule` seems to be outdated/incorrect: the documentation claims this endpoint consumes an `application/json` body using the `RESTAdmissionRuleConfigData` schema, but actually expects a yaml string containing a kubernetes resource.
I have changed the required type to a UTF8-encoded plain text string (like the `/v1/file/compliance/profile/config` endpoint), and added a description and example.

docs: fix api docs for the admission control rules test endpoint

---

controller/rest/assessment.go

See #1969
The current implementation does not explicitly specify whether this endpoint performs a read or write operation. Because of this the access operation is determined by checking the default for the used request method, which results in write since this is a `POST` endpoint. Because of this, you need an API key for a role with `Admission Control (M)` permission to call this endpoint.
By specifying the access operation as `access.AccessOPRead`, an API key using a role with the `Admission Control (V)` permission can be used to test admission control rules.

fix(controller): make admission control rules test endpoint accessible with read permission

---

share/scan/apps.go
share/scan/apps_test.go

- In .NET applications, multiple *.deps.json files may exist, but only the runtime dependencies are relevant for identifying actual vulnerabilities — not the development-time dependencies.
- Currently, NV including all dependencies by default, regardless of whether they’re actually used at runtime.
- Incorporating the `runtime` section into our logic would make this more accurate.
- add `os.Getenv("SCAN_DOTNET_RUNTIME")` to ensure backward compatible
Here are some `.deps.json` snippets for context:
```json
"Microsoft.AspNetCore.Authentication.OpenIdConnect/7.0.0": {
"dependencies": {
"Microsoft.IdentityModel.Protocols.OpenIdConnect": "6.15.1"
},
"runtime": {
"lib/net7.0/Microsoft.AspNetCore.Authentication.OpenIdConnect.dll": {
"assemblyVersion": "7.0.0.0",
"fileVersion": "7.0.22.51819"
} …
```

NVSHAS-9791: read runtime dependency not dev dependency

---

controller/cache/scan.go

workload/node scans: add a KV extension to accompany the large scan reports.

NV9964: Scan fails due to its scan report size

---

controller/rest/repository.go

- forget to early return when scan error, add it to avoid misleading error.

NVSHAS-9911: remove mis-leading info

---

controller/scan/image.go
share/scan/registry/repositories.go

- Wildcard not work properly in quay.io, because quay.io use other api to fetch the repo.
- Only consider the cases for explicitly write quay, since there may not much user using this, plus it requires extra UI change if we make this as a new type.

fix: quay.io is unable to use wildcard properly

---

.github/workflows/release.yml

This PR brings an automated way to generate an intermediate file, which will be used to release a new `update-upgrade-responder` in `EIO` processes 
We want to remove manual actions in order to release a new `update-upgrade-responder`
There is a new step inside [release-workflow](https://github.com/neuvector/neuvector/blob/main/.github/workflows/release.yml)  called `update-upgrade-responder`, which will generate a file `.github/upgrade-responder.json`  located at [.github/](https://github.com/neuvector/neuvector/tree/main/.github) with the same content as `Neuvector` team creates the requests to `EIO`. 
For example:
```json
{
"Versions": [
{
"Name": "v5.4.4",
"ReleaseDate": "2025-05-13T01:31:29.99Z",
"Tags": [
"latest", "5.4.4"
]
}
]
}
```
This new file, will be queried by internal `EIO` …

New step to automate update upgrade-responder

---

agent/engine.go
agent/policy/process.go
agent/probe/process.go
agent/system.go
controller/cache/group.go
controller/cache/profile.go
controller/kv/dispatcher.go
controller/kv/helper.go

The process policy enforcement could fail due to a race condition when setting up the capability flag in per-container storage.
This PR fixes the issue by ensuring that the flag is setup without depending on its parent container.

fix: NVSHAS-10071 policy enforcement issue
