neuvector/neuvector

share/container/containerd.go

containerd: retriving pod's privileged status via cri interface

NV6117: unable to get correct workload privileged info in rke2 setup (POD)

---

controller/common/common.go

Zero-Drift: set default setting to enable Zero-Drift for new services.

Zero-Drift: set default setting to enable Zero-Drift for new services.

---

agent/probe/process.go

Process family trees were incomplete. Implement a pid collector when the FORK events occur,

NV6180 etc.: unexpected Process.Profile.Violation incidents

---

agent/probe/process.go

NV6225: goroutine crash at probe.(*Probe).rootEscalationCheck_uidChange

---

agent/cluster.go
controller/cluster.go
share/utils/utils.go
share/utils/utils_test.go

(1) Add human readable bytes' format display
(2) Improve the message in the memory pressure reports.

MemoryPressure reports: add human readable bytes format

---

agent/probe/process.go
agent/probe/process_test.go
share/system/system_linux.go

Reduce false-positive violations if they are regular maintenance calls from the host.

NV6200: false detect Process.Profile.Violation incidents

---

share/scan/scan_report_test.go

Adjust the DST difference to 11 hours.

Fixed DST issue

---

share/scan/apps.go

The pom.xml has all required dependent JARs information. In the customer's case, we can not find its dependent JARs in this image. Thus, this JAR could not run, either. It might be a mistake for the image developer to put this JAR in this image.
As a result, we will not rely on pom.xml in the future.

NV6208, NV5079: reducing false positive CVE cases on java applications.

---

controller/rest/system.go

add Teams type checking when validate webhook configuration.

add check type for Teams in validateWebhook()

---

controller/api/apis.go
controller/rest/system.go

Move AutoMode REST structure out of the "RESTSystemConfigConfig".

NV5818: Mode automation, REST config data changed.

---

share/auth/auth.go

use group filter which can handle nested group for MS AD

use group filter which can handle nested group for MS AD

---

controller/resource/kubernetes_rbac.go

combine rbac mapping for both native k8s and OpenShift.

refine rbac mapping to avoid confusing; add comments

---

share/scan/apps.go

scan inner "jar" files within a "war" file.

scanner: support WAR's inner jar files scan

---

agent/probe/process.go

The grandparent's and parent's process name could be invalid because their temporary parent process has already left and the PPID needs to be updated to establish the complete process tree

NV6308: patch for grandparent's process name.

---

agent/probe/fsn.go
agent/probe/process.go

(1) Improve the process tree detection to 4 layers. Add some estimates when the processes has already left.
(2) Eliminate false-positive process violations on empty files at the upper layer folders.
(3) Support runtime's storage driver: brfs.

NV6308, NV6351, NV6353, NV6322: unexpected Process.Profile.Violation incidents

---

controller/cache/cache.go

Fix the bug that k8s resource update handler is mistakenly ended

NVSHAS-5200: Add service account that deploys the pod

---

controller/resource/kubernetes_rbac.go

Do not cache user data for users who are mapped to nv's None role

NVSHAS-6155: RBAC: Request to check the api group also while mapping RBAC to nv role

---

agent/probe/process.go

The "docker run", v20.10.7, will init a parallel process along with the root process which shared the container id and cause a false-positive incident in the zero-drift baseline profile.

NV6386: unexpected incidents are reported during docker run to start a container

---

agent/probe/process.go

Make the process evaluation procedure whenever the process profile changes.

NV6304: process profile or group may not learned successfully on oc setup sometimes

---

share/scan/apps.go

This issue caused file parsing to potentially end prematurely causing some files to be ignored.

Fixed an issue with recursive jar parsing

---

agent/probe/process.go

(1) Zero-drift, the suspicious process is not reported as expected. 
(2) While restoring historical processes, the reported flag is not updated correctly. In this case, the process could be reported twice.

NV6391: Zero-drift, missing Container.Suspicious.Process incidents

---

agent/probe/faccess_linux.go
agent/probe/process.go
agent/probe/process_linux.go
share/fsmon/fanotify.go
share/osutil/process_linux.go
share/system/system_linux.go

(1) Redo blocking logic to prevent potential deadlocks.
(2) Add exceptions to some system services.
(3) Support EXEC_PERM on the latest Linux distributions.
(4) Update deny violation messages.

Process blocking improvement

---

agent/probe/process.go
agent/system.go

Mismatched NV service group name.

NV6433: nv protect is unable to disable successfully.

---

agent/probe/process.go

Add qualifiers to allow known privilege user commands.

NV6354: unexpected Host.Privilege.Escalation incident after running sudo visudo

---

agent/probe/process.go

Rewrite the "sudo" and "su" command parser.

NV6454: (updated) unexpected Host.Privilege.Escalation incident

---

agent/probe/faccess_linux.go
agent/probe/process.go

(1) Add option: "FAN_UNLIMITED_QUEUE"
(2) The parent process could be empty when executing a file created with memfd_create() via fexecve() or execveat(AT_EMPTY_PATH).
(3) Move up the function lock to guard the critical section at the complete handleEvents() to prevent multiple access to the main fannotify handle while making the decision calls.
(4) Change the process killer sequence to avoid adding non-container executables into the process blocker.

NV6450: Process blocker improvement: fix potential deadlocks

---

agent/probe/process.go

Remove adding deny rule into the process blocker from the process monitor.

NV6456: a process may hung in the system such as nsenter in protect mode

---

agent/probe/probe.go
agent/probe/process.go

(1) Improve lock and go-routine usages.
(2) Add undetected process exit events in containers to avoid the potential memory leakages,

Improvement: Process Exit events

---

agent/probe/faccess_linux.go

The binary.Read() might sometimes become a synchronized read operation, affecting the mutex usages of the process blocker. Move the mutex allocation after the binary.Read() to avoid the situation.

NV6456 update: a process may hung in the system such as nsenter in protect mode

---

share/scan/scan_utils.go

The repo scan fails to use the correct untared layered paths. Although the repo "secret" scan still works now, it loses some performance by looping all untared folders.

NV6488: Scanner: repo secret scan fails to use the correct layered paths

---

agent/policy/process.go

Add required CIS bench apps in NV protect list.

NV6510: unexpected nv.protect incident on grep command

---

share/auth/auth.go

The nested group filter doesn't work in some MSAD. Add back original group filter and combine nested group filter to ensure the best coverage.

The nested group filter doesn't work in some MSAD.

---

controller/cache/telemetry.go

fix the deadlock introduced by https://github.com/neuvector/neuvector/pull/361

NVSHAS-6629: deadlock found in controller cache package

---

share/utils/timer_wheel.go

The utility function, TimerWheel, failed to calculate the "remaining rounds" at its default 1-hr cycle. Then, it hits the assigned marks twice before firing the timeout notifications.
(1) position the correct locks places to protect the shared variables.
(2) Redo the logics of the slot index and rounds in the timer wheel.

NV6567: group take 2 hours to move to Protect mode when "Monitor to Protect" interval is 1 hour

---

agent/engine.go
agent/pipe/port.go
dp/dpi/dpi_entry.c

conducted unit tests to cover quarantine and policy mode combinations in both cilium and non-cilium environment

NVSHAS-6637, make fix to drop traffic for container in quarantine in cilium cluster

---

share/scan/scan_report.go

Fixed an issue where scan reports could have the wrong severity set.

NVSHAS-5937 scan reports contain wrong severity.

---

controller/cache/domain.go

Fix the incorrect stop condition.

NV6663: part#1 patch, new label on namespace is not added in kv consul

---

share/container/containerd.go
share/container/crio.go

"conatinerd" and "crio"
Adjust the empty time fields (started_at, "finished_at" and "created_at") and make them consistent for both child and parent pods.

NVSHAS-6704: fix started_at and finished_at information in crio and containerd setups

---

controller/cache/node.go

Adjust online status when a new enforcer joins.

NVSHAS-6823: the state of host is unable to become connected from unmanaged

---

controller/opa/regoConversion.go

NVSHAS-6920: string type customized rule with wildcard value cannot work
NVSHAS-6934 deployment creation cannot be denied with "Serive account bound risky role" custom rule when RoleBinding bind ClusterRole

NVSHAS-6920, NVSHAS-6934 couple rego conversion issues

---

controller/rest/admission.go

NVSHAS-6918: Should not allow to create a customized admission control rule when operator is empty
NVSHAS-6919: the value of number type criterion customized rule should be integer

NVSHAS-6918, NVSHAS-6919: add criteria value check

---

controller/opa/regoConversion.go
controller/rest/admission.go

NVSHAS-6965 Unable to add custompath criteria for the valueType is key
NVSHAS-6966 Couple rule conversion issues

NVSHAS-6965, NVSHAS-6966 Couple rule conversion issues

---

agent/probe/process.go

Process filter misses the "nstools" processes running from the "pathWalker". Thus, it created false-positive "NV. Protect" incidents.

NVSHAS-6982, NVSHAS-6643: false positive NV.Protect violations.

---

controller/opa/regoConversion.go
controller/rest/admission.go
controller/rest/admwebhook.go
monitor/monitor.c

NVSHAS-6965 Unable to add custompath criteria for the valueType is key
NVSHAS-6966 Couple rule conversion issues

NVSHAS-6966, NVSHAS-6965: couple rego conversion issues.

---

controller/opa/regoConversion.go
controller/rest/admission.go
controller/rest/admwebhook.go

NVSHAS-7040 allow rule for custom criterion should not be configured
NVSHAS-6999 deployment creation is allowed but deployment cannot be created successfully with some custom criterion cases
NVSHAS-6965 Unable to add custompath criteria for the valueType is key
NVSHAS-6966 Couple rule conversion issues

NVSHAS-7040, NVSHAS-6999, NVSHAS-6965, NVSHAS-6966

---

agent/policy/process.go

Add permission for the new binary: opa.

NV-Protect: Allow opa with the controller container.

---

agent/probe/process.go

Enhance the checking by the process's mounted namespace.

NVSHAS-6643: reduce false-positive NV protect incidents.

---

agent/policy/process.go

Failed to create scanner profile.

NVSHAS-7072: repo, registry, container and standalone scans are all failed due to self protection

---

agent/probe/probe.go
agent/probe/process.go

Logics changes to search the ancestries.

NVSHAS-6643 #3: unexpected Process.Profile.Violation incident in NV.Protect group

---

controller/opa/regoConversion.go

NVSHAS-7116 Match wrong role definition

NVSHAS-7116 Match wrong role definition

---

agent/probe/process.go

Patch unprotected osutil.GetAllUsers().

NVSHAS-7563: a potential map write panic in the reportEscalation()

---

controller/api/apis.yaml

Updating the swagger def'n to cover the new element in the request.

NVSHAS-7608 - Adding `baseline_profile` to request path `/v1/system/request`

---

agent/system.go
controller/cache/dlp_rule.go
controller/rest/dlp_rule.go

allow DLP rule with empty pattern

NVSHAS-5759: allow DLP rule with empty pattern

---

share/container/containerd.go
share/container/cri_client.go
share/container/crio.go
share/container/types.go

Support CRI API v1 (a sole API for cri-o 1.26).
(1) CRI API v1 is the priority.
(2) CRI API v1alphav2 is also supported as backward compatibility.

NVSHAS-7586: Neuvector doesn't support cri-o > 1.26 and Openshift 4.11

---

share/fsmon/monitor.go

New inotify notifications will bypass the original exception file check. Move the exception check to the main event handler to avoid those false-positive file events.

NVSHAS-7745: unexpected NV.Protect incidents on our cert files

---

dp/dpi/parsers/dpi_sqlinjection.c

Add 1 new signature to detect "or 1" follows by comment symbols. i.e.
" or 1 -- //
" OR 1 ORDER BY id DESC --
' or 1 #'
' or 1/*
' or 1 in (select @@version)--{}

"NVSHAS-6533: Add 1 new signature for SQLi detection"

---

agent/dp/ctrl.go

Fix goroutine crash at dpSendMsgExSilent()

"NVSHAS-7811: fix goroutine crash"

---

templates/podTemplate.json

NVSHAS-7731-add imagePullPolicy for pod template

---

agent/engine.go
agent/policy/process.go
agent/probe/process.go

(1) Add CSP pod protection.
(2) Simplify self-protection and exception decisions.

NVSHAS-7706: avoid intercept the traffic for neuvector csp adapter

---

.github/workflows/unitest.yaml

Use GitHub Action to validate OpenAPI file, apis.yaml

NVSHAS-7841 Use tool to validate apis.yaml

---

controller/api/apis.go
controller/kv/helper.go
controller/rest/repository.go
controller/rest/sigstore.go

NVSHAS-6217: update collection response types to array

---

agent/engine.go
agent/policy/process.go

Add self-protection for the registry adapter container.

NVSHAS-8005: Update self-protection for registry adapter

---

agent/policy/process.go

This incident happened in the controller and it is from the monitor's checkup function.

NVSHAS-8000: unexpected NV.Protect incidents are found

---

agent/probe/process.go

The log entry were filling up the logs and we wanted to lower the noise at info level.

NVSHAS-7965 - Change orphan debug logs from trace to debug level  

---

dp/dpi/parsers/dpi_mysql.c

For mysql parser with capability flag CLIENT_PLUGIN_AUTH set, add the MYSQL_AUTH_SWITCH_REQUEST state. After MYSQL_LOGIN_RESPONSE, if the next packet's first byte is "0xFE", then process it as MYSQL_AUTH_SWITCH_REQUEST packet and go to MYSQL_AUTH_SWITCH_RESPONSE state. Otherwise, just go to MYSQL_REQUEST state.

NVSHAS-7963: Fix mysql parser

---

controller/api/apis.yaml

Add **fqdn** field in the Violation for API document

NVSHAS-5703 & NVSHAS-5365: API document change for Violation

---

controller/cache/admission.go
controller/cache/admission_test.go
controller/nvk8sapi/nvvalidatewebhookcfg/admission/admission.go
controller/rest/admwebhook.go
share/criteria.go

Support annotations, so users can setup admission rule using UI, CLI and API.

NVSHAS-7483: support annotations

---

dp/ctrl.c

Add NULL pointer check for th_ip_fqdn_storage_map

[NVSHAS-8192] Fix dp crash at dp_ctrl_update_ip_fqdn_storage()

---

controller/rest/auth.go
share/utils/utils.go
share/utils/utils_test.go

Use installation-specific key to encrypt/decrypt JWT token.

NVSHAS-8210: use installation-specific key

---

controller/api/apis.go
controller/api/apis.yaml
controller/rest/process.go

NVSHAS-8091: remove process_replace_list entry from PATCH(v1/process_profile/:name) API

---

agent/cluster.go
controller/api/apis.go
controller/api/apis.yaml
controller/cache/object.go
controller/rest/workload.go
share/clus_apis.go
share/container/containerd.go
share/container/cri_client.go
share/container/crio.go
share/container/docker.go
share/container/types.go

Backend provider: Include "image created at" time into the REST API. 
Update the "apis.yaml" as well.

NVSHAS-7728: NeuVector should provide container image build date in Assets -> Container details

---

controller/cache/file_monitor.go

Replace the receiving channels with slices to avoid the deadlock condition.

Controller: rewrite the flow of the learning file rule requests.

---

share/scan/registry.go

Empty signature information returns no error instead of a registry API error.

NVHSAS-8302: fix manifest scan error for unsigned images

---

controller/scan/image.go
controller/scan/registry.go

These changes will check whether an image has a signature before requiring a signature scan whenever the sigstore configuration changes.

NVSHAS-8310: don't scan unsigned images when sigstore configuration changes

---

agent/probe/process.go

Remove the socat from the predefined suspicious process list.

NVSHAS-8121: suggest not report Container.Suspicious.Process incident for socat processes

---

controller/api/apis.go
controller/api/internal_apis.go
controller/cache/compliance.go
controller/cache/connect.go

Add conversation detail data into /v1/internal/system. UI can use it to display more info in dashboard

NVSHAS-8204: Add RESTConversationReportEntry into RESTExposedEndpoint

---

controller/rest/server.go

After change, now we can accept empty key/cert when SLO is not enabled. Also we can accept null cert/key as long as the end result is a valid pair.

NVSHAS-8448 refine validation in server API

---

agent/nvbench/container.tmpl
agent/nvbench/docker-bench-security/tests/1_host_configuration.sh
agent/nvbench/docker-bench-security/tests/2_docker_daemon_configuration.sh
agent/nvbench/docker-bench-security/tests/4_container_images.sh
agent/nvbench/docker-bench-security/tests/7_docker_swarm_configuration.sh
agent/nvbench/docker-bench-security/tests/99_community_checks.sh
agent/nvbench/host.tmpl

- Improve the warning messages on docker bench

NVSHAS-8284 Warning status for some Compliance checks which however were satisfied

---

agent/policy/process.go

NVSHAS-8589: unexpected NV.Protect incidents are found on yq and sort commands

---

share/osutil/file_linux.go

- Adjust the bug level of the GetContainerRealFilePath

NVSHAS-8585 Adjust the bug level of the GetContainerRealFilePath

---

share/cluster/consul.go

A global object, watchPlans, which is accessed by multiple reader and writer go routines, is not protected by a mutex or lock.  This causes random crash and potential unexpected behavior when watching consul changes.
When it crashes, the call stack would be like this:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x1a6bbbf]
```
`add=0x50` shows that one of element retrieved from the map becomes null, despite all items inserted are non-null.
Two POCs are implemented to show that being without protection is the root cause. 
- Reader + Writer: https://go.dev/play/p/K4dq64QWTIy
- Crash in 30% chance.
- Two writers: https://go.dev/play/p/p-PbvhERzwu
- Crash in after about 30k attempts. 
Both POC crashed …

NVSHAS-8591 fix watchPlans race condition

---

agent/bench.go
agent/nvbench/kube_runner.tmpl
agent/nvbench/ocp/rh-1.4.0/master/1_control_plane_components.yaml
agent/nvbench/ocp/rh-1.4.0/master/3_control_plane_configuration.yaml
agent/nvbench/ocp/rh-1.4.0/master/5_policies.yaml
agent/nvbench/ocp/rh-1.4.0/worker/4_worker_nodes.yaml
agent/nvbench/rh_runner.tmpl

1. Fix open shift yaml
2. Improve runner template
3. Improve BenchLoop to make cisYAMLMode to be true in default for future convieniece. 
enforcer: [docker.io/pohanhuangtw/enforcer:8460](http://docker.io/pohanhuangtw/enforcer:8460)
controller: [docker.io/pohanhuangtw/controller:8460](http://docker.io/pohanhuangtw/controller:8460)

NVSHAS-8460 bug fix open shift yaml

---

controller/api/apis.go
controller/rest/vulasset.go
db/vulassets.go

1. support change sort column and type during pagination
2. scoreV2 and scoreV3 query
3. add last_modified_timestamp

NVSHAS-7720-Enhance_UI_Performance_support_change_sort

---

controller/api/apis.go
db/models.go
db/vulassets.go

1. adjust quick filter behavior, it is now applied on existing query session.
2. do not count vul record when it is removed by VPF

NVSHAS-7720-Enhance_UI_Performance, adjust quick filter behavior

---

controller/rest/vulasset.go
controller/rest/vulasset_perf.go
db/vulassets.go

1. fix cve score query error
2. make perf_test easier to use

NVSHAS-7720-Enhance_UI_Performance_fix_query

---

agent/policy/process.go

Update an allowed process rule.

NVSHAS-8622: unexpected NV.Protect incidents is found on support command

---

agent/policy/process.go

Adjust process rules on ARM-based NV pods.

Add/Update process rules for ARM64 images

---

controller/cache/automode.go
controller/cache/learn.go
controller/cache/log.go
controller/cache/sync.go

This reverts commit fbd1215f23537b5c734133e56dc65148cec18e19.

Revert "NVSHAS-8613 repeated sigsegv in one controller"

---

controller/cache/scan.go
controller/rest/vulasset.go
controller/scan/registry.go
db/assetvuls.go
db/models.go
db/querystats.go
db/vulassets.go

1. Minimize mutex lock time. 
2. Prioritize UI queries for improved responsiveness during heavy loads. 
3. Implement retries when the database is locked under heavy loads.

NVSHAS-8624-Vulnerabilities_Cluster_node_is_unstable

---

controller/rest/vulasset.go
db/models.go
db/vulassets.go

NVSHAS-8653 Add impact sort
NVSHAS-8669 Fix Internal Server Error in pagination

NVSHAS-8653 Add impact sort, NVSHAS-8669 Fix Internal Server Error in pagination

---

share/container/crio.go

Patch protections on the "nil" structures

NVSHAS-8693: goroutine crash at container.(*crioDriver).getContainer()

---

share/scan/apps.go

Adds support to parse php composer.lock files to find vulnerable php components.

NVSHAS-6483 add support for php composer

---

agent/policy/process.go

NVSHAS-8709: unexpected NV.Protect incidents is found on support command

---

agent/probe/faccess_linux.go
agent/probe/process.go

Please read the logic changes in the JIRA case.

NVSHAS-6740: Improvement of zero-drift baseline profile by enforcing the learned list in protect mode 

---

agent/engine.go
share/system/sidekick/net_linux.go

add interface nil check for Link

NVSHAS-8720: fix agent crash at main.intfHostMonitorLoop

---

dp/dpi/sig/dpi_search.c

Add pointer valid check for dlp_ptr in dpi

NVSHAS-8677 Fix enforcer crash for arm64

---

Makefile
agent/bench.go
monitor/monitor.c

1. Consolidate the scripts into scripts folder 
2. shell scrips in /usr/local/bin/scripts/
controller: [docker.io/pohanhuangtw/controller:8692]
enforcer: [docker.io/pohanhuangtw/enforcer:8692]

NVSHAS-8692: NV Protect: consolidate all shell scripts into scripts folder 

---

agent/nvbench/kubernetes-cis-benchmark/cis-1.23/master/5_policies.yaml
agent/nvbench/kubernetes-cis-benchmark/cis-1.24/master/5_policies.yaml
agent/nvbench/kubernetes-cis-benchmark/cis-1.8.0/master/5_policies.yaml

1. Remove $ in echo, which the root cause of the bug
enforcer: [docker.io/pohanhuangtw/enforcer:8701]

NVSHAS-8701 - Add \$ for unexpected NV.Protect incidents is found on paste command

---

agent/agent.go
agent/bench.go
agent/engine.go
agent/group_profile.go
agent/policy/process.go
agent/probe/incident_reporter.go
agent/probe/probe.go
agent/probe/process.go
agent/probe/process_test.go
agent/probe/types.go
agent/task.go
share/fsmon/fanotify_linux.go

The improvement helps restrict rules for nv pods files. Some executable and script folders will trigger alerts and block the bench operations.

NVSHAS-8676: Review: NV Protect improvement

---

agent/nvbench/kubernetes-cis-benchmark/cis-1.23/master/5_policies.yaml
agent/nvbench/kubernetes-cis-benchmark/cis-1.24/master/5_policies.yaml
agent/nvbench/kubernetes-cis-benchmark/cis-1.6.0/master/5_policies.yaml
agent/nvbench/kubernetes-cis-benchmark/cis-1.8.0/master/5_policies.yaml
agent/nvbench/ocp/rh-1.4.0/master/5_policies.yaml

1. Fix the truncate msg in manual by {\"\\\\n\"}
enforcer: [docker.io/pohanhuangtw/enforcer:8780]

NVSHAS-8780 - Fix the truncate msg in manual

---

agent/probe/fsn.go

Re-implement the lock sequences among modules.

NVSHAS-8803: container is somehow unable to add to workload successfully frequently

---

agent/agent.go
controller/controller.go
upgrader/Makefile

1. Rename controllerCancel() to internalCertCancel()
2. Fix a crash when rotation feature is disabled.
3. Use dynamic linking instead.

fix: a few issues

---

share/system/cgroup_linux.go
share/system/cgroup_test.go

Fixes https://github.com/neuvector/neuvector/issues/1277

fix parsing of container id in container in container environments

---

controller/cache/log.go
controller/controller.go
controller/rest/mock_test.go
share/scan/compliance.go
share/scan/compliance_test.go
share/scan/scan_report.go

1. isolate the call of GetImageBencheMeta from scanner to get Imagebench only. 
2. Improve the unit-test for compliance map.
controller: [docker.io/hhcs9527/controller:8926]

NVSHAS-8926 -Scanner read not-exist path when stand alone mode

---

share/scan/apps.go

Incorrect map key caused map comparison to fail during comparison.

NVSHAS-6483 fix incorrect map key for php parser

---

controller/remote_repository/github.go
controller/resource/kubernetes_auth.go
controller/scan/ibmcloud.go
share/orchestration/kubernetes.go

During code review for NVSHAS-8968, a few extra potential memory leaks are found.  This PR is to fix these issues.

fix: NVSHAS-8968 memory leak found during code review

---

controller/remote_repository/github.go

Fix the incorrect error handling.

NVSHAS-9001 goroutine crash

---

share/scan/apps.go

Add R-language module parser from their manifest files. 
Sample:
{
"Name": "base",  
"Version": "4.0.5",
"Source": "r"
},

NVSHAS-8995: add R-lang module parser

---

agent/probe/process.go

Apply the allow status when it was a risky child process.

NVSHAS-9023: PP: Child process of sshd is still reported after white listing them in Basic and discovery mode

---

share/container/types.go

K8s only: users can assign the runtime socket path while deploying enforcer pods to bypass the errors.
According to this situation, we need an improvement of the auto-runtime-finder.
(1) The customized k8s environment does not use the generic "kubelet" and its node comes with unused "docker" engine (which cause the "container list is empty" issue).
(2) Add k3s case.
(3) Remove assuming docker socket if it does not find the path.

NVSHAS-9011: "Container list is empty" error happen in enforcer pod in GKE+Cilium cluster

---

share/scan/apps.go

container scans:
(1) Prioritized the POM detection. 
(2) To remove the duplicates from the JAR files
(3) Filter the meaningless module name as the "jar:jar"

NVSHAS-9022, NVSHAS-9031: duplicate module entries by a JAR file

---

agent/agent.go
agent/bench.go
controller/controller.go
controller/rest/mock_test.go
share/clus_apis.go
share/global/global.go
share/scan/compliance.go
share/types.go

1. Add cloudPlatform to detect which cloud platform we are running in order to run the CIS correctly.
2. And able to run the Rancher on EKS correctly.

[NVSHAS-9042] Add cloudPlatform as new variable to avoid Racher is not detected on EKS.

---

agent/agent.go

A timing issue. Need to adjust the call sequence to avoid the non-initialized "probe object".

NVSHAS-9147: goroutine crash at main.(*Bench).BenchLoop()

---

agent/nvbench/kubernetes-cis-benchmark/aks-1.4.0/worker/3_worker_nodes.yaml
agent/nvbench/kubernetes-cis-benchmark/cis-1.23/worker/4_worker_nodes.yaml
agent/nvbench/kubernetes-cis-benchmark/cis-1.24/worker/4_worker_nodes.yaml
agent/nvbench/kubernetes-cis-benchmark/cis-1.6.0/worker/4_worker_nodes.yaml
agent/nvbench/kubernetes-cis-benchmark/cis-1.8.0/worker/4_worker_nodes.yaml
agent/nvbench/kubernetes-cis-benchmark/eks-1.4.0/worker/3_worker_nodes.yaml
agent/nvbench/kubernetes-cis-benchmark/gke-1.4.0/worker/3_worker_nodes.yaml
share/scan/testdata/mock-cis/worker/4_worker_nodes.yaml

- Change CIS test items to check  --event-qps  > 0.

[NVSHAS-9111] NV should check  --event-qps  > 0.

---

agent/engine.go
agent/probe/fsn.go
agent/probe/process.go

Add temporary folder exceptions for FSN monitor.

NVSHAS-9130: unexpected Container.Package.Updated incidents are found after a specific container is started

---

share/scan/scan_utils.go

Copy the db file to enforcer's temp folder and make it being properly scanned.

NVSHAS-9091: patch container scan

---

controller/grpc.go

Modify the "ps" command to include the consul server process.

NVSHAS-9173: Show the "ps" result of the "consul" in the /v1/controller/.../counter

---

agent/probe/process.go

This is a false-positive event from the enforcer itself. Add exceptions on the file location checks.

NVSHAS-9175: unexpected NV.Protect incidents is found on grep command

---

controller/grpc.go

Reverts neuvector/neuvector#1467

Revert "NVSHAS-8242: update critical vul support flag"

---

controller/access/access.go
controller/access/access_test.go
controller/api/access.go
controller/api/apis.go
controller/cache/scan.go
controller/rest/rest.go
controller/rest/scanner.go
controller/rest/vulasset.go
controller/scan/registry.go
db/assetvuls.go
db/models.go
db/querystats.go
db/querystats_test.go
db/vulassets.go

- Replace previous PR (now closed) - https://github.com/neuvector/neuvector/pull/1466
- Resolve the issues on previous PR, detail log can be found at https://github.com/neuvector/neuvector/pull/1466
- Temporarily revert CVE critical level support

NVSHAS-8857-support image pagination rev

---

controller/rest/bench.go
share/scan/compliance.go

When we set up the compliance profile, the result is not aligned in node > compliance.
Set up the compliance profile, the result is aligned in node > compliance.

[NVSHAS-8799] Fix the compliance profile filter when filter V1 result.

---

controller/common/output.go

1.  Organize the body to improve readanility and find key details
Expected result

[NVSHAS-6980] Organize the body to improve readanility and find key details

---

agent/agent.go
agent/engine.go
agent/probe/probe.go
agent/probe/process.go
agent/task.go
controller/api/apis.go
controller/rest/device.go
monitor/monitor.c
share/clus_apis.go
share/cluster/intfs.go
share/fsmon/monitor.go

1. Add an ENV variable for deployment setting syslog level
2. Add a new option to set syslog level in runtime for enforcer configuration

NVSHAS-7687: Add syslog level setting for enforcer

---

controller/cache/group.go
controller/resource/kubernetes_rbac.go
controller/resource/kubernetes_resource.go

Based on https://github.com/neuvector/neuvector/pull/1516, fix RBAC alerts on cert upgrader.

NVSHAS-9194 fix rbac alerts

---

share/global/global.go

In rancher eks, some node is unable to detect the eks.
Extend the existing logic to get the cloud platform when parsing the platform out.
Test on the eks cluster, and make sure the detection correctly.

[NVSHAS-8461] Improve SetGlobalObjects to detect the clolud platform correctly

---

agent/bench.go
controller/api/apis.go
controller/cache/object.go
controller/cluster.go
controller/controller.go
controller/orch.go
share/clus_apis.go
share/scan/compliance.go
share/scan/compliance_test.go

- Remove prime config after update the controller
- Add ReadPimeConfig to help support debug, for support bundle
- Deploy on k8s
- Simulate node die, and make sure the support match the result

[NVSHAS-8799] Remove prime config after update the controller, and add ReadPimeConfig to help support debug

---

agent/agent.go
agent/engine.go
agent/probe/incident_reporter.go
agent/probe/process.go
agent/task.go
share/fsmon/fanotify_linux.go
share/fsmon/monitor.go

(1) Improve NV Protect by open access controls.
(2) ZD: fix an insider-modified binary hole during Monitor mode.

NVSHAS-9391, 9325, 9033: misc process controls on NV Protect and ZD.

---

controller/rest/file_monitor.go
share/fsmon/fanotify_linux.go

Allow predefined file to be deleted.

NVSHAS-9403: REST allows deleting file monitor rules

---

agent/policy/process.go
agent/probe/process.go

Remap the executable file paths

NV Protect: rewrite the process rules based on the BCI-micro upgrade

---

agent/policy/process.go

NV Protect: rule updates

---

controller/rest/bench.go
share/scan/compliance.go
share/scan/scan_report.go

Add the fix patch for updating the imagebench with compliance profile

[NVSHAS-8799] Improve the updating of imagebench with compliance profile and naming

---

Makefile

It is a combination images: ALPINE (AMD64) and BCI-micro (ARM64).

Use base image tag pre54

---

share/scan/apps.go

There was a logic issue with how jar parsing was handled. A jar may contain multiple pom.properties files, if they are not duplicates then they should be added rather than overwritten. In some cases this was causing much of the data to be lost.

NVSHAS-9416 fix several issues with jar parsing

---

controller/api/apis.go
controller/api/internal_apis.go
controller/cache/compliance.go
controller/cache/config.go
controller/cache/group.go
controller/cache/group_test.go
controller/cache/interface.go
controller/cache/profile.go
controller/common/common.go
controller/kv/upgrade.go
controller/rest/configmap.go
controller/rest/crdsecurityrule.go
controller/rest/group.go
controller/rest/group_test.go
controller/rest/mock_test.go
controller/rest/system.go
share/clus_apis.go

cherry-pick from https://github.com/neuvector/neuvector/pull/1513 to 5.4.0 branch for NVSHAS-8583

For 5.4.0 branch, NVSHAS-8583, separate network policy mode and profile mode at per group level

---

agent/agent.go
controller/api/apis.go
controller/api/apis.yaml
controller/cache/cache.go
controller/cache/config.go
controller/controller.go
controller/nvk8sapi/neuvectorcrd/crd.go
controller/resource/nvsecurityrule_def.go
controller/rest/crdsecurityrule.go
monitor/monitor.c

NVSHAS-9369 Add debug log category via helm deployment support for controller
NVSHAS-9440: support separate network mode and Process and File mode in CRD

Cherry-pick NVSHAS-9369 & NVSHAS-9440 from main to 5.4.1 branch

---

share/system/cgroup_linux.go

This case is on the "a newer crio + cgroup v1" with non-privilege controller. A workaround is applied.

NVSHAS-9447: Controller/Scanner pods crashing - "Unsupported system Exit"

---

share/scan/apps.go

NVSHAS-9416 fix several issues with jar parsing

Cherry-pick pull request #1556 from Acmarr/main to 5.4.1 branch

---

agent/group_profile.go

The k8s POD label is only shown on the POD container so its children (app) container, without a matching label, will not be considered as a propagating member. In this situation, we are confused with the profile rules by the custom group.
This PR will enable the POD label to affect its children containers since they should share the same profile rules under the POD.

NVSHAS-9467: custom group defined by the pod label does not propagate its profile data on the children containers.

---

agent/group_profile.go

NVSHAS-9467: custom group defined by the pod label does not propagate its profile data on the children containers

---

agent/engine.go
agent/probe/process.go

NVSHAS-9325: NVProtect: Manager/Controller is not blocking not-allowed commands

---

controller/atmo/atmo.go
controller/atmo/atmo_test.go
controller/cache/automode.go
controller/cache/group.go

(1) Enable the Mode Automation on the ProfileMode and PolicyMode per learned groups.
(2) Remove "^M" from two original go files

NVSHAS-9484: Enable Mode Automation on the separate policy and profile modes

---

controller/atmo/atmo.go
controller/atmo/atmo_test.go
controller/cache/automode.go
controller/cache/group.go

backported.
(1) Enable the Mode Automation on the ProfileMode and PolicyMode per learned groups.
(2) Remove "^M" from two original go files

NVSHAS-9484: Enable Mode Automation on the separate policy and profile mode

---

agent/engine.go

Enable the block process feature of the NV Protect.

Enhanced NV Protect: block unallowed processes.

---

.github/workflows/golangci-lint.yml
.golangci.yml

Provided a set of default linters as the first step.

feat: enable golangci-lint

---

controller/rest/ibmsa_test.go

for https://sonarcloud.io/project/issues?open=AY6JVRT9jFlUEPxw8pQ0&id=codacy-open-source-projects-scans_neuvector

Change implicit mockup test data to explicit mockup test data 

---

controller/kv/config.go
controller/kv/create.go
controller/kv/dispatcher.go
controller/kv/endpoint.go
controller/kv/helper.go
controller/kv/mock.go
controller/kv/policy.go
controller/kv/registry.go
controller/kv/upgrade.go
controller/kv/upgrade_test.go

NVSHAS-9525: Resolve existing Go linter issues in the NeuVector repository 

---

controller/kv/config.go
controller/kv/endpoint.go
controller/kv/helper.go
controller/kv/registry.go
controller/kv/upgrade.go

NVSHAS-9525: Resolve existing Go linter issues in the NeuVector repository

---

agent/engine.go

Need more investigations to find its failed issue in the mini tests.

Disable NV Protect block feature

---

controller/cache/scan.go
controller/scan/scan.go

This PR fixes a few lint issues.

fix: NVSHAS-9525 lint issues

---

controller/rest/auth.go

Change to return http.StatusUnauthorized 401 when jwtToken/apiKey expires

NVSHAS-9558: JWT token expire reports http.StatusRequestTimeout 408

---

controller/rest/group.go

NVSHAS-8824: User fails to delete own groups, cannot create namespace-scoped groups

---

controller/cache/config.go

Fix "set controller <leader_controller_id> debug" will set debug category as empty to disable debug log.

NVSHAS-9600: Fix disable controller debug category

---

.github/workflows/unitest.yaml
controller/api/apis.yaml
controller/api/internal_apis.yaml

1. Use redocly/cli to replace swagger-validator-action.
2. Upgrade related actions and golang version.
3. Fixed a few issues in api docs.
4. Validate internal_apis.yaml

fix: NVSHAS-9624 rewrite swagger validation

---

controller/rest/crdsecurityrule.go

It is caused by incorrect type conversion introduced in 5.4.0 only

NVSHAS-9645: pre-existing CRD processing fails

---

controller/cache/scan.go

NVSHAS-9592: requeue in-progress workloads on db update

---

upgrader/main.go

The 5.4.2 version for https://github.com/neuvector/neuvector/pull/1676

fix: NVSHAS-9443 ArgoCD issue

---

share/scan/apps.go
share/scan/apps_test.go

Fixes an issue where module count and contents could be inconsistent. Added a new unit test to cover this as well as updating  TestParseDotNetModuleNameVersion test.

NVSHAS-9700/NVSHAS-9699 Retool logic for parseDotNetPackage

---

share/cluster/consul.go

This commit disables consul gRPC server

fix: NVSHAS-9705 disable consul gRPC server

---

controller/grpc.go

- Cherry pick https://github.com/neuvector/neuvector/pull/1694
- Cherry pick https://github.com/neuvector/neuvector/pull/1695

Cherry pick NVSHAS-9681

---

controller/api/apis.go
controller/cache/cache.go
db/models.go
db/vulassets.go

[release/5.4.2] Cherry-pick updates

NVSHAS-9710: Add feed rating in Risk Page

---

controller/cache/scan.go
controller/rest/vulasset.go
db/assetvuls.go

NVSHAS-9696:Inconsistent colour indication of assets on vulnerability page

---

controller/cache/cache.go
controller/cache/object.go

Enhance /v1/workload endpoint to lookup both wlCacheMap and nvwlCacheMap caches when fetching workload information.

NVSHAS-9649: Container link produces 404 response code in security event

---

controller/scan/dockerhub.go
controller/scan/image.go
controller/scan/jfrog.go
controller/scan/registry.go

1. Cherry pick https://github.com/neuvector/neuvector/pull/1724

Cherry pick NVSHAS-9507-fix

---

package/Dockerfile.controller
package/Dockerfile.enforcer

Help Sam Wang to update consul version to 1.16.4p1. The original commit is holyspectral@adacd3e#diff-f6915a4f6b0adf7568f77fd8c72dd1c0a3d37352c6c93dcd5630a180ba2f95c5R55

Cherry pick: Update consul version to 1.16.4p1

---

controller/access/access.go
controller/access/access_test.go
controller/api/internal_apis.go
controller/rest/rest.go
controller/rest/system.go

Add missing REST API handler on backend

NVSHAS-9740: Dashboard: Improve your score produces 405 error

---

agent/probe/faccess_linux.go
agent/probe/process.go
share/clus_apis.go

(1) During Monitor mode, set alerts on not listed family processes. 
(2) Add process violation messages on above incidents

NVSHAS-9751: add not-listed family process rule alert

---

package/Dockerfile.controller
package/Dockerfile.enforcer

Help Sam Wang to update consul version to 1.16.4p1. The original commit is https://github.com/holyspectral/neuvector/commit/adacd3eb36a8c3fe0f6f77dde5f66833b3a73c68#diff-f6915a4f6b0adf7568f77fd8c72dd1c0a3d37352c6c93dcd5630a180ba2f95c5R55

Update consul version to 1.16.4p1

---

agent/agent.go
agent/types.go
monitor/monitor.c

Add disable file monitor env flag
The env ENF_NO_FILE_PROFILE will disable file monitor.

NVSHAS-9756: disable file monitor

---

share/scan/scan_utils.go
share/utils/extract.go

1. Add extraction related functions for scanner
2. Move MakeTar to extract.go

NVSHAS-9584: Add extraction related functions

---

agent/system.go
agent/timer.go

Apply slices.Clone() to improve the GC efficiency

NVSHAS-9772: Memory mgt with golang API: slices.Clone()

---

agent/probe/process.go
share/fsmon/monitor.go

1. patch polymorphic case on controller's healthchecks.
2. remove unnecessary debug traces.

NVSHAS-9325 follow-up: misc fix

---

agent/nvbench/docker-bench-security/Dockerfile
agent/nvbench/docker-bench-security/distros/Dockerfile.alpine

update CODEOWNERS to skip files under root

chore: update apline version for docker bench

---

Makefile
agent/bench.go
agent/nvbench/kubernetes-cis-benchmark/cis-rke2-1.8.0/master/1_control_plane_components.yaml
agent/nvbench/kubernetes-cis-benchmark/cis-rke2-1.8.0/master/2_etcd.yaml
agent/nvbench/kubernetes-cis-benchmark/cis-rke2-1.8.0/master/3_control_plane_configuration.yaml
agent/nvbench/kubernetes-cis-benchmark/cis-rke2-1.8.0/master/5_policies.yaml
agent/nvbench/kubernetes-cis-benchmark/cis-rke2-1.8.0/worker/4_worker_nodes.yaml
agent/nvbench/utils/utils.sh
share/scan/compliance.go

- Add benchmark scripts to support cis benchmark in RKE2 with error details improvement
- RKE2 v1.30.5+rke2r1
- K8s 1.30

[NVSHAS-9668] Support cis benchmark in RKE2 env

---

controller/cache/group.go

(1) A deadlock situation happened during the controller's leadership changes. 
(2) The dispatcher refers cacher's data and its caller should hold the cacher mutex 
(3) Make sure that callers of the dispatcher are free of cacher's mutex.

NVSHAS-9810: dispatcher's caller should not hold cacher's mutex.

---

monitor/monitor.c

Make sure monitor can generate meaningful log when component is killed by a signal.  Some sample:
kill -9:
```
2025-02-13T19:39:37|MON|Process ctrl exit status -1, signal 9, pid=7
```
kill -HUP:
```
2025-02-13T19:40:10|MON|Process ctrl exit status -1, signal 1, pid=113
```

fix: log more information about signal

---

controller/api/apis.go
controller/api/apis.yaml
controller/cache/log.go
controller/cache/scan.go
controller/cache/scan_test.go
controller/rest/scanner.go
share/clus_apis.go

- when the auto scan is true, the others needs to be true.
- https://github.com/neuvector/neuvector/pull/1828

[NVSHAS-9826] fix cold start with auto-scan true bug

---

controller/api/apis.go
controller/cache/cache.go
controller/rest/vulasset.go
db/models.go
db/vulassets.go
share/scan/scan_report.go

Add a status to indicate "pending" when the CVEDB is still loading.

NVSHAS-9265 Incomplete and Incorrect Vulnerability Scan Results

---

agent/probe/process.go

The process monitor might have different command forms.

NVSHAS-9842: NV Protect false-positive events on the cli command

---

agent/engine.go
agent/policy/process.go
agent/probe/process.go
agent/system.go
controller/cache/group.go
controller/cache/profile.go
controller/kv/dispatcher.go
controller/kv/helper.go

(1) Patch missing learning short-lived pods by extending active container life cycle. 
(2) Maintain enforcing process groups (mode monitor/protect) at nodes 
(3) It is improving to block processes with a valid enforcing process profile.

NVSHAS-9828: improvement for short-lived pods

---

controller/rest/longpoll_test.go

- Unstable due to the pollworker and scheduleJobToQueue run in concurrent, add channel in mockTask to resolve the unstable issue.

[ci-fix] Fix the unitest unstable

---

.github/workflows/release.yml
.github/workflows/unitest.yaml

Pin GH dependencies

---

share/fsmon/monitor.go

Reorder the criteria: set the file-modified flags have a higher priority.

NVSHAS-9874: File modification of /etc/hostname is not detected

---

agent/engine.go
agent/policy/process.go
agent/probe/process.go
agent/system.go
controller/cache/group.go
controller/cache/profile.go
controller/kv/dispatcher.go
controller/kv/helper.go

This reverts commit 1291769fb9d2ab781b92864bc8c3595ddc6016eb.

Revert "NVSHAS-9828: improvement for short-lived pods"

---

share/container/containerd.go
share/container/types.go

The latest kubelet has some depreciated parameters.

NVSHAS-9876: adapt the changes of the kublet v1.32

---

share/container/containerd.go

The containerd server does not include the cri interface

Runtime driver: containerd has a panic condition

---

.github/workflows/renovate-vault.yml

renovate is supposed to run on weekdays instead of weekend.

fix: update incorrect renovate schedule

---

Makefile
agent/policy/network.go

1. Add mutex for unknown_ip_map
2. Bump up to scala-3.3.5 accompany with manager's change

NVSHAS-9913: Fix goroutine panic for unknown_ip_map

---

agent/agent.go
agent/engine.go
agent/probe/probe.go
share/fsmon/monitor.go

(1) Patch NeuVector POD identification
(2) Fix the trace log usages at module level

NV9920: Neuvector components are reported in container and group page

---

agent/grpc.go
agent/workerlet/pathWalker/pathWalker.go
agent/workerlet/types.go
share/scan/scan_utils.go

Recreated a PR to reduce the confusions.
The original PR is https://github.com/neuvector/neuvector/pull/1933

NV9905: k8s workload scan

---

controller/rest/longpoll.go
controller/rest/longpoll_test.go
controller/rest/repository.go

- The new logging is confusing (from customer), so I make some change to improve the logging

fix: improve the error logging

---

controller/cache/scan.go

workload/node scans: add a KV extension to accompany the large scan reports.

NV9964: Scan fails due to its scan report size

---

controller/nvk8sapi/nvvalidatewebhookcfg/admission/admission.go
controller/rest/admwebhook.go

enforcer issue has been fixed in prior version.
this PR is for improving logging & events aggregation found in customer's env

NVSHAS-9969: concurrent map writes results in enforcer component restart

---

controller/cache/scan.go

NVSHAS-9964: Scan fails after upgrading NeuVector to 5.4.1 due to report size

---

agent/probe/process.go

Reworked based on https://github.com/neuvector/neuvector/commit/06eefb0aa33e6942ccb57aaeab774847c6fe83d7

fix: NVSHAS-9981 update zero-drift behavior

---

controller/api/admission_api.go
controller/resource/nvsecurityrule_def.go
controller/rest/admission.go

- move export admission control struct to api package.

fix: admission converter dependency

---

agent/timer.go

Enforce connectionMap to include high-priority connections (LEARN, VIOLATE, DENY)

NVSHAS-10031: Improve connection report sending
